// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/ctr_boss_flags.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTRBOSSFlags struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MarkArrivedPrivileged bool                   `protobuf:"varint,1,opt,name=mark_arrived_privileged,json=markArrivedPrivileged,proto3" json:"mark_arrived_privileged,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CTRBOSSFlags) Reset() {
	*x = CTRBOSSFlags{}
	mi := &file_boss_v2_ctr_boss_flags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTRBOSSFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTRBOSSFlags) ProtoMessage() {}

func (x *CTRBOSSFlags) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_ctr_boss_flags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTRBOSSFlags.ProtoReflect.Descriptor instead.
func (*CTRBOSSFlags) Descriptor() ([]byte, []int) {
	return file_boss_v2_ctr_boss_flags_proto_rawDescGZIP(), []int{0}
}

func (x *CTRBOSSFlags) GetMarkArrivedPrivileged() bool {
	if x != nil {
		return x.MarkArrivedPrivileged
	}
	return false
}

var File_boss_v2_ctr_boss_flags_proto protoreflect.FileDescriptor

const file_boss_v2_ctr_boss_flags_proto_rawDesc = "" +
	"\n" +
	"\x1cboss/v2/ctr_boss_flags.proto\x12\aboss.v2\"F\n" +
	"\fCTRBOSSFlags\x126\n" +
	"\x17mark_arrived_privileged\x18\x01 \x01(\bR\x15markArrivedPrivilegedB\x90\x01\n" +
	"\vcom.boss.v2B\x11CtrBossFlagsProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_ctr_boss_flags_proto_rawDescOnce sync.Once
	file_boss_v2_ctr_boss_flags_proto_rawDescData []byte
)

func file_boss_v2_ctr_boss_flags_proto_rawDescGZIP() []byte {
	file_boss_v2_ctr_boss_flags_proto_rawDescOnce.Do(func() {
		file_boss_v2_ctr_boss_flags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_ctr_boss_flags_proto_rawDesc), len(file_boss_v2_ctr_boss_flags_proto_rawDesc)))
	})
	return file_boss_v2_ctr_boss_flags_proto_rawDescData
}

var file_boss_v2_ctr_boss_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_boss_v2_ctr_boss_flags_proto_goTypes = []any{
	(*CTRBOSSFlags)(nil), // 0: boss.v2.CTRBOSSFlags
}
var file_boss_v2_ctr_boss_flags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boss_v2_ctr_boss_flags_proto_init() }
func file_boss_v2_ctr_boss_flags_proto_init() {
	if File_boss_v2_ctr_boss_flags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_ctr_boss_flags_proto_rawDesc), len(file_boss_v2_ctr_boss_flags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_ctr_boss_flags_proto_goTypes,
		DependencyIndexes: file_boss_v2_ctr_boss_flags_proto_depIdxs,
		MessageInfos:      file_boss_v2_ctr_boss_flags_proto_msgTypes,
	}.Build()
	File_boss_v2_ctr_boss_flags_proto = out.File
	file_boss_v2_ctr_boss_flags_proto_goTypes = nil
	file_boss_v2_ctr_boss_flags_proto_depIdxs = nil
}
