// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/delete_file.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        uint64                 `protobuf:"varint,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	PlatformType  PlatformType           `protobuf:"varint,3,opt,name=platform_type,json=platformType,proto3,enum=boss.v2.PlatformType" json:"platform_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_boss_v2_delete_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_delete_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_boss_v2_delete_file_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileRequest) GetDataId() uint64 {
	if x != nil {
		return x.DataId
	}
	return 0
}

func (x *DeleteFileRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *DeleteFileRequest) GetPlatformType() PlatformType {
	if x != nil {
		return x.PlatformType
	}
	return PlatformType_PLATFORM_TYPE_UNSPECIFIED
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_boss_v2_delete_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_delete_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_boss_v2_delete_file_proto_rawDescGZIP(), []int{1}
}

var File_boss_v2_delete_file_proto protoreflect.FileDescriptor

const file_boss_v2_delete_file_proto_rawDesc = "" +
	"\n" +
	"\x19boss/v2/delete_file.proto\x12\aboss.v2\x1a\x1bboss/v2/platform_type.proto\"\x88\x01\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\x04R\x06dataId\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x12:\n" +
	"\rplatform_type\x18\x03 \x01(\x0e2\x15.boss.v2.PlatformTypeR\fplatformType\"\x14\n" +
	"\x12DeleteFileResponseB\x8e\x01\n" +
	"\vcom.boss.v2B\x0fDeleteFileProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_delete_file_proto_rawDescOnce sync.Once
	file_boss_v2_delete_file_proto_rawDescData []byte
)

func file_boss_v2_delete_file_proto_rawDescGZIP() []byte {
	file_boss_v2_delete_file_proto_rawDescOnce.Do(func() {
		file_boss_v2_delete_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_delete_file_proto_rawDesc), len(file_boss_v2_delete_file_proto_rawDesc)))
	})
	return file_boss_v2_delete_file_proto_rawDescData
}

var file_boss_v2_delete_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_v2_delete_file_proto_goTypes = []any{
	(*DeleteFileRequest)(nil),  // 0: boss.v2.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 1: boss.v2.DeleteFileResponse
	(PlatformType)(0),          // 2: boss.v2.PlatformType
}
var file_boss_v2_delete_file_proto_depIdxs = []int32{
	2, // 0: boss.v2.DeleteFileRequest.platform_type:type_name -> boss.v2.PlatformType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_v2_delete_file_proto_init() }
func file_boss_v2_delete_file_proto_init() {
	if File_boss_v2_delete_file_proto != nil {
		return
	}
	file_boss_v2_platform_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_delete_file_proto_rawDesc), len(file_boss_v2_delete_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_delete_file_proto_goTypes,
		DependencyIndexes: file_boss_v2_delete_file_proto_depIdxs,
		MessageInfos:      file_boss_v2_delete_file_proto_msgTypes,
	}.Build()
	File_boss_v2_delete_file_proto = out.File
	file_boss_v2_delete_file_proto_goTypes = nil
	file_boss_v2_delete_file_proto_depIdxs = nil
}
