// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/file_ctr.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileCTR struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Deleted            bool                     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DataId             uint64                   `protobuf:"varint,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // * Used for distinguishing files internally
	TaskId             string                   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BossAppId          string                   `protobuf:"bytes,4,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	SupportedCountries []string                 `protobuf:"bytes,5,rep,name=supported_countries,json=supportedCountries,proto3" json:"supported_countries,omitempty"`
	SupportedLanguages []string                 `protobuf:"bytes,6,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	Attributes         *FileAttributes          `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CreatorPid         uint32                   `protobuf:"varint,8,opt,name=creator_pid,json=creatorPid,proto3" json:"creator_pid,omitempty"`
	Name               string                   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Hash               string                   `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	SerialNumber       uint64                   `protobuf:"varint,11,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	PayloadContents    []*PayloadContentInfoCTR `protobuf:"bytes,12,rep,name=payload_contents,json=payloadContents,proto3" json:"payload_contents,omitempty"`
	Size               uint64                   `protobuf:"varint,13,opt,name=size,proto3" json:"size,omitempty"`
	CreatedTimestamp   uint64                   `protobuf:"varint,14,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"`
	UpdatedTimestamp   uint64                   `protobuf:"varint,15,opt,name=updated_timestamp,json=updatedTimestamp,proto3" json:"updated_timestamp,omitempty"`
	Flags              *CTRBOSSFlags            `protobuf:"bytes,16,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileCTR) Reset() {
	*x = FileCTR{}
	mi := &file_boss_v2_file_ctr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCTR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCTR) ProtoMessage() {}

func (x *FileCTR) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_file_ctr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCTR.ProtoReflect.Descriptor instead.
func (*FileCTR) Descriptor() ([]byte, []int) {
	return file_boss_v2_file_ctr_proto_rawDescGZIP(), []int{0}
}

func (x *FileCTR) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *FileCTR) GetDataId() uint64 {
	if x != nil {
		return x.DataId
	}
	return 0
}

func (x *FileCTR) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FileCTR) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *FileCTR) GetSupportedCountries() []string {
	if x != nil {
		return x.SupportedCountries
	}
	return nil
}

func (x *FileCTR) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

func (x *FileCTR) GetAttributes() *FileAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *FileCTR) GetCreatorPid() uint32 {
	if x != nil {
		return x.CreatorPid
	}
	return 0
}

func (x *FileCTR) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileCTR) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileCTR) GetSerialNumber() uint64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *FileCTR) GetPayloadContents() []*PayloadContentInfoCTR {
	if x != nil {
		return x.PayloadContents
	}
	return nil
}

func (x *FileCTR) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileCTR) GetCreatedTimestamp() uint64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *FileCTR) GetUpdatedTimestamp() uint64 {
	if x != nil {
		return x.UpdatedTimestamp
	}
	return 0
}

func (x *FileCTR) GetFlags() *CTRBOSSFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

var File_boss_v2_file_ctr_proto protoreflect.FileDescriptor

const file_boss_v2_file_ctr_proto_rawDesc = "" +
	"\n" +
	"\x16boss/v2/file_ctr.proto\x12\aboss.v2\x1a\x1cboss/v2/ctr_boss_flags.proto\x1a\x1dboss/v2/file_attributes.proto\x1a&boss/v2/payload_content_info_ctr.proto\"\xe4\x04\n" +
	"\aFileCTR\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\x04R\x06dataId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vboss_app_id\x18\x04 \x01(\tR\tbossAppId\x12/\n" +
	"\x13supported_countries\x18\x05 \x03(\tR\x12supportedCountries\x12/\n" +
	"\x13supported_languages\x18\x06 \x03(\tR\x12supportedLanguages\x127\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x17.boss.v2.FileAttributesR\n" +
	"attributes\x12\x1f\n" +
	"\vcreator_pid\x18\b \x01(\rR\n" +
	"creatorPid\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\n" +
	" \x01(\tR\x04hash\x12#\n" +
	"\rserial_number\x18\v \x01(\x04R\fserialNumber\x12I\n" +
	"\x10payload_contents\x18\f \x03(\v2\x1e.boss.v2.PayloadContentInfoCTRR\x0fpayloadContents\x12\x12\n" +
	"\x04size\x18\r \x01(\x04R\x04size\x12+\n" +
	"\x11created_timestamp\x18\x0e \x01(\x04R\x10createdTimestamp\x12+\n" +
	"\x11updated_timestamp\x18\x0f \x01(\x04R\x10updatedTimestamp\x12+\n" +
	"\x05flags\x18\x10 \x01(\v2\x15.boss.v2.CTRBOSSFlagsR\x05flagsB\x8b\x01\n" +
	"\vcom.boss.v2B\fFileCtrProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_file_ctr_proto_rawDescOnce sync.Once
	file_boss_v2_file_ctr_proto_rawDescData []byte
)

func file_boss_v2_file_ctr_proto_rawDescGZIP() []byte {
	file_boss_v2_file_ctr_proto_rawDescOnce.Do(func() {
		file_boss_v2_file_ctr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_file_ctr_proto_rawDesc), len(file_boss_v2_file_ctr_proto_rawDesc)))
	})
	return file_boss_v2_file_ctr_proto_rawDescData
}

var file_boss_v2_file_ctr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_boss_v2_file_ctr_proto_goTypes = []any{
	(*FileCTR)(nil),               // 0: boss.v2.FileCTR
	(*FileAttributes)(nil),        // 1: boss.v2.FileAttributes
	(*PayloadContentInfoCTR)(nil), // 2: boss.v2.PayloadContentInfoCTR
	(*CTRBOSSFlags)(nil),          // 3: boss.v2.CTRBOSSFlags
}
var file_boss_v2_file_ctr_proto_depIdxs = []int32{
	1, // 0: boss.v2.FileCTR.attributes:type_name -> boss.v2.FileAttributes
	2, // 1: boss.v2.FileCTR.payload_contents:type_name -> boss.v2.PayloadContentInfoCTR
	3, // 2: boss.v2.FileCTR.flags:type_name -> boss.v2.CTRBOSSFlags
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_boss_v2_file_ctr_proto_init() }
func file_boss_v2_file_ctr_proto_init() {
	if File_boss_v2_file_ctr_proto != nil {
		return
	}
	file_boss_v2_ctr_boss_flags_proto_init()
	file_boss_v2_file_attributes_proto_init()
	file_boss_v2_payload_content_info_ctr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_file_ctr_proto_rawDesc), len(file_boss_v2_file_ctr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_file_ctr_proto_goTypes,
		DependencyIndexes: file_boss_v2_file_ctr_proto_depIdxs,
		MessageInfos:      file_boss_v2_file_ctr_proto_msgTypes,
	}.Build()
	File_boss_v2_file_ctr_proto = out.File
	file_boss_v2_file_ctr_proto_goTypes = nil
	file_boss_v2_file_ctr_proto_depIdxs = nil
}
