// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/list_tasks.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_boss_v2_list_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_list_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_boss_v2_list_tasks_proto_rawDescGZIP(), []int{0}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_boss_v2_list_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_list_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_boss_v2_list_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_boss_v2_list_tasks_proto protoreflect.FileDescriptor

const file_boss_v2_list_tasks_proto_rawDesc = "" +
	"\n" +
	"\x18boss/v2/list_tasks.proto\x12\aboss.v2\x1a\x12boss/v2/task.proto\"\x12\n" +
	"\x10ListTasksRequest\"8\n" +
	"\x11ListTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.boss.v2.TaskR\x05tasksB\x8d\x01\n" +
	"\vcom.boss.v2B\x0eListTasksProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_list_tasks_proto_rawDescOnce sync.Once
	file_boss_v2_list_tasks_proto_rawDescData []byte
)

func file_boss_v2_list_tasks_proto_rawDescGZIP() []byte {
	file_boss_v2_list_tasks_proto_rawDescOnce.Do(func() {
		file_boss_v2_list_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_list_tasks_proto_rawDesc), len(file_boss_v2_list_tasks_proto_rawDesc)))
	})
	return file_boss_v2_list_tasks_proto_rawDescData
}

var file_boss_v2_list_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_v2_list_tasks_proto_goTypes = []any{
	(*ListTasksRequest)(nil),  // 0: boss.v2.ListTasksRequest
	(*ListTasksResponse)(nil), // 1: boss.v2.ListTasksResponse
	(*Task)(nil),              // 2: boss.v2.Task
}
var file_boss_v2_list_tasks_proto_depIdxs = []int32{
	2, // 0: boss.v2.ListTasksResponse.tasks:type_name -> boss.v2.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_v2_list_tasks_proto_init() }
func file_boss_v2_list_tasks_proto_init() {
	if File_boss_v2_list_tasks_proto != nil {
		return
	}
	file_boss_v2_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_list_tasks_proto_rawDesc), len(file_boss_v2_list_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_list_tasks_proto_goTypes,
		DependencyIndexes: file_boss_v2_list_tasks_proto_depIdxs,
		MessageInfos:      file_boss_v2_list_tasks_proto_msgTypes,
	}.Build()
	File_boss_v2_list_tasks_proto = out.File
	file_boss_v2_list_tasks_proto_goTypes = nil
	file_boss_v2_list_tasks_proto_depIdxs = nil
}
