// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/list_files_wup.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFilesWUPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	Country       *string                `protobuf:"bytes,3,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Language      *string                `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Any           bool                   `protobuf:"varint,5,opt,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesWUPRequest) Reset() {
	*x = ListFilesWUPRequest{}
	mi := &file_boss_v2_list_files_wup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesWUPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesWUPRequest) ProtoMessage() {}

func (x *ListFilesWUPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_list_files_wup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesWUPRequest.ProtoReflect.Descriptor instead.
func (*ListFilesWUPRequest) Descriptor() ([]byte, []int) {
	return file_boss_v2_list_files_wup_proto_rawDescGZIP(), []int{0}
}

func (x *ListFilesWUPRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListFilesWUPRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *ListFilesWUPRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *ListFilesWUPRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *ListFilesWUPRequest) GetAny() bool {
	if x != nil {
		return x.Any
	}
	return false
}

type ListFilesWUPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileWUP             `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesWUPResponse) Reset() {
	*x = ListFilesWUPResponse{}
	mi := &file_boss_v2_list_files_wup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesWUPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesWUPResponse) ProtoMessage() {}

func (x *ListFilesWUPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_list_files_wup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesWUPResponse.ProtoReflect.Descriptor instead.
func (*ListFilesWUPResponse) Descriptor() ([]byte, []int) {
	return file_boss_v2_list_files_wup_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesWUPResponse) GetFiles() []*FileWUP {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_boss_v2_list_files_wup_proto protoreflect.FileDescriptor

const file_boss_v2_list_files_wup_proto_rawDesc = "" +
	"\n" +
	"\x1cboss/v2/list_files_wup.proto\x12\aboss.v2\x1a\x16boss/v2/file_wup.proto\"\xb9\x01\n" +
	"\x13ListFilesWUPRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x12\x1d\n" +
	"\acountry\x18\x03 \x01(\tH\x00R\acountry\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x10\n" +
	"\x03any\x18\x05 \x01(\bR\x03anyB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_language\">\n" +
	"\x14ListFilesWUPResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.boss.v2.FileWUPR\x05filesB\x90\x01\n" +
	"\vcom.boss.v2B\x11ListFilesWupProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_list_files_wup_proto_rawDescOnce sync.Once
	file_boss_v2_list_files_wup_proto_rawDescData []byte
)

func file_boss_v2_list_files_wup_proto_rawDescGZIP() []byte {
	file_boss_v2_list_files_wup_proto_rawDescOnce.Do(func() {
		file_boss_v2_list_files_wup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_list_files_wup_proto_rawDesc), len(file_boss_v2_list_files_wup_proto_rawDesc)))
	})
	return file_boss_v2_list_files_wup_proto_rawDescData
}

var file_boss_v2_list_files_wup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_v2_list_files_wup_proto_goTypes = []any{
	(*ListFilesWUPRequest)(nil),  // 0: boss.v2.ListFilesWUPRequest
	(*ListFilesWUPResponse)(nil), // 1: boss.v2.ListFilesWUPResponse
	(*FileWUP)(nil),              // 2: boss.v2.FileWUP
}
var file_boss_v2_list_files_wup_proto_depIdxs = []int32{
	2, // 0: boss.v2.ListFilesWUPResponse.files:type_name -> boss.v2.FileWUP
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_v2_list_files_wup_proto_init() }
func file_boss_v2_list_files_wup_proto_init() {
	if File_boss_v2_list_files_wup_proto != nil {
		return
	}
	file_boss_v2_file_wup_proto_init()
	file_boss_v2_list_files_wup_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_list_files_wup_proto_rawDesc), len(file_boss_v2_list_files_wup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_list_files_wup_proto_goTypes,
		DependencyIndexes: file_boss_v2_list_files_wup_proto_depIdxs,
		MessageInfos:      file_boss_v2_list_files_wup_proto_msgTypes,
	}.Build()
	File_boss_v2_list_files_wup_proto = out.File
	file_boss_v2_list_files_wup_proto_goTypes = nil
	file_boss_v2_list_files_wup_proto_depIdxs = nil
}
