// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/payload_content_ctr.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadContentCTR struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TitleId         uint64                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	ContentDatatype uint32                 `protobuf:"varint,2,opt,name=content_datatype,json=contentDatatype,proto3" json:"content_datatype,omitempty"`
	NsDataId        uint32                 `protobuf:"varint,3,opt,name=ns_data_id,json=nsDataId,proto3" json:"ns_data_id,omitempty"`
	Version         uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Content         []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayloadContentCTR) Reset() {
	*x = PayloadContentCTR{}
	mi := &file_boss_v2_payload_content_ctr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadContentCTR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadContentCTR) ProtoMessage() {}

func (x *PayloadContentCTR) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_payload_content_ctr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadContentCTR.ProtoReflect.Descriptor instead.
func (*PayloadContentCTR) Descriptor() ([]byte, []int) {
	return file_boss_v2_payload_content_ctr_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadContentCTR) GetTitleId() uint64 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *PayloadContentCTR) GetContentDatatype() uint32 {
	if x != nil {
		return x.ContentDatatype
	}
	return 0
}

func (x *PayloadContentCTR) GetNsDataId() uint32 {
	if x != nil {
		return x.NsDataId
	}
	return 0
}

func (x *PayloadContentCTR) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PayloadContentCTR) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_boss_v2_payload_content_ctr_proto protoreflect.FileDescriptor

const file_boss_v2_payload_content_ctr_proto_rawDesc = "" +
	"\n" +
	"!boss/v2/payload_content_ctr.proto\x12\aboss.v2\"\xab\x01\n" +
	"\x11PayloadContentCTR\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\x04R\atitleId\x12)\n" +
	"\x10content_datatype\x18\x02 \x01(\rR\x0fcontentDatatype\x12\x1c\n" +
	"\n" +
	"ns_data_id\x18\x03 \x01(\rR\bnsDataId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontentB\x95\x01\n" +
	"\vcom.boss.v2B\x16PayloadContentCtrProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_payload_content_ctr_proto_rawDescOnce sync.Once
	file_boss_v2_payload_content_ctr_proto_rawDescData []byte
)

func file_boss_v2_payload_content_ctr_proto_rawDescGZIP() []byte {
	file_boss_v2_payload_content_ctr_proto_rawDescOnce.Do(func() {
		file_boss_v2_payload_content_ctr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_payload_content_ctr_proto_rawDesc), len(file_boss_v2_payload_content_ctr_proto_rawDesc)))
	})
	return file_boss_v2_payload_content_ctr_proto_rawDescData
}

var file_boss_v2_payload_content_ctr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_boss_v2_payload_content_ctr_proto_goTypes = []any{
	(*PayloadContentCTR)(nil), // 0: boss.v2.PayloadContentCTR
}
var file_boss_v2_payload_content_ctr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boss_v2_payload_content_ctr_proto_init() }
func file_boss_v2_payload_content_ctr_proto_init() {
	if File_boss_v2_payload_content_ctr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_payload_content_ctr_proto_rawDesc), len(file_boss_v2_payload_content_ctr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_payload_content_ctr_proto_goTypes,
		DependencyIndexes: file_boss_v2_payload_content_ctr_proto_depIdxs,
		MessageInfos:      file_boss_v2_payload_content_ctr_proto_msgTypes,
	}.Build()
	File_boss_v2_payload_content_ctr_proto = out.File
	file_boss_v2_payload_content_ctr_proto_goTypes = nil
	file_boss_v2_payload_content_ctr_proto_depIdxs = nil
}
