// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/platform_type.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformType int32

const (
	PlatformType_PLATFORM_TYPE_UNSPECIFIED PlatformType = 0
	PlatformType_PLATFORM_TYPE_CTR         PlatformType = 1
	PlatformType_PLATFORM_TYPE_WUP         PlatformType = 2
)

// Enum value maps for PlatformType.
var (
	PlatformType_name = map[int32]string{
		0: "PLATFORM_TYPE_UNSPECIFIED",
		1: "PLATFORM_TYPE_CTR",
		2: "PLATFORM_TYPE_WUP",
	}
	PlatformType_value = map[string]int32{
		"PLATFORM_TYPE_UNSPECIFIED": 0,
		"PLATFORM_TYPE_CTR":         1,
		"PLATFORM_TYPE_WUP":         2,
	}
)

func (x PlatformType) Enum() *PlatformType {
	p := new(PlatformType)
	*p = x
	return p
}

func (x PlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_boss_v2_platform_type_proto_enumTypes[0].Descriptor()
}

func (PlatformType) Type() protoreflect.EnumType {
	return &file_boss_v2_platform_type_proto_enumTypes[0]
}

func (x PlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformType.Descriptor instead.
func (PlatformType) EnumDescriptor() ([]byte, []int) {
	return file_boss_v2_platform_type_proto_rawDescGZIP(), []int{0}
}

var File_boss_v2_platform_type_proto protoreflect.FileDescriptor

const file_boss_v2_platform_type_proto_rawDesc = "" +
	"\n" +
	"\x1bboss/v2/platform_type.proto\x12\aboss.v2*[\n" +
	"\fPlatformType\x12\x1d\n" +
	"\x19PLATFORM_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PLATFORM_TYPE_CTR\x10\x01\x12\x15\n" +
	"\x11PLATFORM_TYPE_WUP\x10\x02B\x90\x01\n" +
	"\vcom.boss.v2B\x11PlatformTypeProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_platform_type_proto_rawDescOnce sync.Once
	file_boss_v2_platform_type_proto_rawDescData []byte
)

func file_boss_v2_platform_type_proto_rawDescGZIP() []byte {
	file_boss_v2_platform_type_proto_rawDescOnce.Do(func() {
		file_boss_v2_platform_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_platform_type_proto_rawDesc), len(file_boss_v2_platform_type_proto_rawDesc)))
	})
	return file_boss_v2_platform_type_proto_rawDescData
}

var file_boss_v2_platform_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_boss_v2_platform_type_proto_goTypes = []any{
	(PlatformType)(0), // 0: boss.v2.PlatformType
}
var file_boss_v2_platform_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boss_v2_platform_type_proto_init() }
func file_boss_v2_platform_type_proto_init() {
	if File_boss_v2_platform_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_platform_type_proto_rawDesc), len(file_boss_v2_platform_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_platform_type_proto_goTypes,
		DependencyIndexes: file_boss_v2_platform_type_proto_depIdxs,
		EnumInfos:         file_boss_v2_platform_type_proto_enumTypes,
	}.Build()
	File_boss_v2_platform_type_proto = out.File
	file_boss_v2_platform_type_proto_goTypes = nil
	file_boss_v2_platform_type_proto_depIdxs = nil
}
