// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/update_task.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTaskData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	TitleId       uint64                 `protobuf:"varint,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Interval      uint32                 `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskData) Reset() {
	*x = UpdateTaskData{}
	mi := &file_boss_v2_update_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskData) ProtoMessage() {}

func (x *UpdateTaskData) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_update_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskData.ProtoReflect.Descriptor instead.
func (*UpdateTaskData) Descriptor() ([]byte, []int) {
	return file_boss_v2_update_task_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTaskData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskData) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *UpdateTaskData) GetTitleId() uint64 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *UpdateTaskData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTaskData) GetInterval() uint32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *UpdateTaskData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	UpdateData    *UpdateTaskData        `protobuf:"bytes,3,opt,name=update_data,json=updateData,proto3" json:"update_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_boss_v2_update_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_update_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_boss_v2_update_task_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *UpdateTaskRequest) GetUpdateData() *UpdateTaskData {
	if x != nil {
		return x.UpdateData
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_boss_v2_update_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_update_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_boss_v2_update_task_proto_rawDescGZIP(), []int{2}
}

var File_boss_v2_update_task_proto protoreflect.FileDescriptor

const file_boss_v2_update_task_proto_rawDesc = "" +
	"\n" +
	"\x19boss/v2/update_task.proto\x12\aboss.v2\"\xb1\x01\n" +
	"\x0eUpdateTaskData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\x04R\atitleId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\rR\binterval\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"}\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x128\n" +
	"\vupdate_data\x18\x03 \x01(\v2\x17.boss.v2.UpdateTaskDataR\n" +
	"updateData\"\x14\n" +
	"\x12UpdateTaskResponseB\x8e\x01\n" +
	"\vcom.boss.v2B\x0fUpdateTaskProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_update_task_proto_rawDescOnce sync.Once
	file_boss_v2_update_task_proto_rawDescData []byte
)

func file_boss_v2_update_task_proto_rawDescGZIP() []byte {
	file_boss_v2_update_task_proto_rawDescOnce.Do(func() {
		file_boss_v2_update_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_update_task_proto_rawDesc), len(file_boss_v2_update_task_proto_rawDesc)))
	})
	return file_boss_v2_update_task_proto_rawDescData
}

var file_boss_v2_update_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_boss_v2_update_task_proto_goTypes = []any{
	(*UpdateTaskData)(nil),     // 0: boss.v2.UpdateTaskData
	(*UpdateTaskRequest)(nil),  // 1: boss.v2.UpdateTaskRequest
	(*UpdateTaskResponse)(nil), // 2: boss.v2.UpdateTaskResponse
}
var file_boss_v2_update_task_proto_depIdxs = []int32{
	0, // 0: boss.v2.UpdateTaskRequest.update_data:type_name -> boss.v2.UpdateTaskData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_v2_update_task_proto_init() }
func file_boss_v2_update_task_proto_init() {
	if File_boss_v2_update_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_update_task_proto_rawDesc), len(file_boss_v2_update_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_update_task_proto_goTypes,
		DependencyIndexes: file_boss_v2_update_task_proto_depIdxs,
		MessageInfos:      file_boss_v2_update_task_proto_msgTypes,
	}.Build()
	File_boss_v2_update_task_proto = out.File
	file_boss_v2_update_task_proto_goTypes = nil
	file_boss_v2_update_task_proto_depIdxs = nil
}
