// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/v2/upload_file_wup.proto

package bossv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileWUPRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BossAppId          string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	SupportedCountries []string               `protobuf:"bytes,3,rep,name=supported_countries,json=supportedCountries,proto3" json:"supported_countries,omitempty"`
	SupportedLanguages []string               `protobuf:"bytes,4,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	Attributes         *FileAttributes        `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Name               string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	NotifyOnNew        []string               `protobuf:"bytes,8,rep,name=notify_on_new,json=notifyOnNew,proto3" json:"notify_on_new,omitempty"`
	NotifyLed          bool                   `protobuf:"varint,9,opt,name=notify_led,json=notifyLed,proto3" json:"notify_led,omitempty"`
	ConditionPlayed    uint64                 `protobuf:"varint,10,opt,name=condition_played,json=conditionPlayed,proto3" json:"condition_played,omitempty"`
	AutoDelete         bool                   `protobuf:"varint,11,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Data               []byte                 `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	NameEqualsDataId   bool                   `protobuf:"varint,13,opt,name=name_equals_data_id,json=nameEqualsDataId,proto3" json:"name_equals_data_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadFileWUPRequest) Reset() {
	*x = UploadFileWUPRequest{}
	mi := &file_boss_v2_upload_file_wup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileWUPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileWUPRequest) ProtoMessage() {}

func (x *UploadFileWUPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_upload_file_wup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileWUPRequest.ProtoReflect.Descriptor instead.
func (*UploadFileWUPRequest) Descriptor() ([]byte, []int) {
	return file_boss_v2_upload_file_wup_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileWUPRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadFileWUPRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *UploadFileWUPRequest) GetSupportedCountries() []string {
	if x != nil {
		return x.SupportedCountries
	}
	return nil
}

func (x *UploadFileWUPRequest) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

func (x *UploadFileWUPRequest) GetAttributes() *FileAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UploadFileWUPRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileWUPRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadFileWUPRequest) GetNotifyOnNew() []string {
	if x != nil {
		return x.NotifyOnNew
	}
	return nil
}

func (x *UploadFileWUPRequest) GetNotifyLed() bool {
	if x != nil {
		return x.NotifyLed
	}
	return false
}

func (x *UploadFileWUPRequest) GetConditionPlayed() uint64 {
	if x != nil {
		return x.ConditionPlayed
	}
	return 0
}

func (x *UploadFileWUPRequest) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *UploadFileWUPRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileWUPRequest) GetNameEqualsDataId() bool {
	if x != nil {
		return x.NameEqualsDataId
	}
	return false
}

type UploadFileWUPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileWUP               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileWUPResponse) Reset() {
	*x = UploadFileWUPResponse{}
	mi := &file_boss_v2_upload_file_wup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileWUPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileWUPResponse) ProtoMessage() {}

func (x *UploadFileWUPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_v2_upload_file_wup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileWUPResponse.ProtoReflect.Descriptor instead.
func (*UploadFileWUPResponse) Descriptor() ([]byte, []int) {
	return file_boss_v2_upload_file_wup_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileWUPResponse) GetFile() *FileWUP {
	if x != nil {
		return x.File
	}
	return nil
}

var File_boss_v2_upload_file_wup_proto protoreflect.FileDescriptor

const file_boss_v2_upload_file_wup_proto_rawDesc = "" +
	"\n" +
	"\x1dboss/v2/upload_file_wup.proto\x12\aboss.v2\x1a\x1dboss/v2/file_attributes.proto\x1a\x16boss/v2/file_wup.proto\"\xe4\x03\n" +
	"\x14UploadFileWUPRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x12/\n" +
	"\x13supported_countries\x18\x03 \x03(\tR\x12supportedCountries\x12/\n" +
	"\x13supported_languages\x18\x04 \x03(\tR\x12supportedLanguages\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.boss.v2.FileAttributesR\n" +
	"attributes\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\"\n" +
	"\rnotify_on_new\x18\b \x03(\tR\vnotifyOnNew\x12\x1d\n" +
	"\n" +
	"notify_led\x18\t \x01(\bR\tnotifyLed\x12)\n" +
	"\x10condition_played\x18\n" +
	" \x01(\x04R\x0fconditionPlayed\x12\x1f\n" +
	"\vauto_delete\x18\v \x01(\bR\n" +
	"autoDelete\x12\x12\n" +
	"\x04data\x18\f \x01(\fR\x04data\x12-\n" +
	"\x13name_equals_data_id\x18\r \x01(\bR\x10nameEqualsDataId\"=\n" +
	"\x15UploadFileWUPResponse\x12$\n" +
	"\x04file\x18\x01 \x01(\v2\x10.boss.v2.FileWUPR\x04fileB\x91\x01\n" +
	"\vcom.boss.v2B\x12UploadFileWupProtoP\x01Z1github.com/PretendoNetwork/grpc/go/boss/v2;bossv2\xa2\x02\x03BXX\xaa\x02\aBoss.V2\xca\x02\aBoss\\V2\xe2\x02\x13Boss\\V2\\GPBMetadata\xea\x02\bBoss::V2b\x06proto3"

var (
	file_boss_v2_upload_file_wup_proto_rawDescOnce sync.Once
	file_boss_v2_upload_file_wup_proto_rawDescData []byte
)

func file_boss_v2_upload_file_wup_proto_rawDescGZIP() []byte {
	file_boss_v2_upload_file_wup_proto_rawDescOnce.Do(func() {
		file_boss_v2_upload_file_wup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_v2_upload_file_wup_proto_rawDesc), len(file_boss_v2_upload_file_wup_proto_rawDesc)))
	})
	return file_boss_v2_upload_file_wup_proto_rawDescData
}

var file_boss_v2_upload_file_wup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_v2_upload_file_wup_proto_goTypes = []any{
	(*UploadFileWUPRequest)(nil),  // 0: boss.v2.UploadFileWUPRequest
	(*UploadFileWUPResponse)(nil), // 1: boss.v2.UploadFileWUPResponse
	(*FileAttributes)(nil),        // 2: boss.v2.FileAttributes
	(*FileWUP)(nil),               // 3: boss.v2.FileWUP
}
var file_boss_v2_upload_file_wup_proto_depIdxs = []int32{
	2, // 0: boss.v2.UploadFileWUPRequest.attributes:type_name -> boss.v2.FileAttributes
	3, // 1: boss.v2.UploadFileWUPResponse.file:type_name -> boss.v2.FileWUP
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_boss_v2_upload_file_wup_proto_init() }
func file_boss_v2_upload_file_wup_proto_init() {
	if File_boss_v2_upload_file_wup_proto != nil {
		return
	}
	file_boss_v2_file_attributes_proto_init()
	file_boss_v2_file_wup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_v2_upload_file_wup_proto_rawDesc), len(file_boss_v2_upload_file_wup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_v2_upload_file_wup_proto_goTypes,
		DependencyIndexes: file_boss_v2_upload_file_wup_proto_depIdxs,
		MessageInfos:      file_boss_v2_upload_file_wup_proto_msgTypes,
	}.Build()
	File_boss_v2_upload_file_wup_proto = out.File
	file_boss_v2_upload_file_wup_proto_goTypes = nil
	file_boss_v2_upload_file_wup_proto_depIdxs = nil
}
