// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: friends/v2/accept_friend_request_rpc.proto

package friendsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptFriendRequestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FriendRequestId uint64                 `protobuf:"varint,1,opt,name=friend_request_id,json=friendRequestId,proto3" json:"friend_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_friends_v2_accept_friend_request_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_accept_friend_request_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friends_v2_accept_friend_request_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptFriendRequestRequest) GetFriendRequestId() uint64 {
	if x != nil {
		return x.FriendRequestId
	}
	return 0
}

type AcceptFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_friends_v2_accept_friend_request_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_accept_friend_request_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_friends_v2_accept_friend_request_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptFriendRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_friends_v2_accept_friend_request_rpc_proto protoreflect.FileDescriptor

const file_friends_v2_accept_friend_request_rpc_proto_rawDesc = "" +
	"\n" +
	"*friends/v2/accept_friend_request_rpc.proto\x12\n" +
	"friends.v2\"H\n" +
	"\x1aAcceptFriendRequestRequest\x12*\n" +
	"\x11friend_request_id\x18\x01 \x01(\x04R\x0ffriendRequestId\"7\n" +
	"\x1bAcceptFriendRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\xaf\x01\n" +
	"\x0ecom.friends.v2B\x1bAcceptFriendRequestRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/friends/v2;friendsv2\xa2\x02\x03FXX\xaa\x02\n" +
	"Friends.V2\xca\x02\n" +
	"Friends\\V2\xe2\x02\x16Friends\\V2\\GPBMetadata\xea\x02\vFriends::V2b\x06proto3"

var (
	file_friends_v2_accept_friend_request_rpc_proto_rawDescOnce sync.Once
	file_friends_v2_accept_friend_request_rpc_proto_rawDescData []byte
)

func file_friends_v2_accept_friend_request_rpc_proto_rawDescGZIP() []byte {
	file_friends_v2_accept_friend_request_rpc_proto_rawDescOnce.Do(func() {
		file_friends_v2_accept_friend_request_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_v2_accept_friend_request_rpc_proto_rawDesc), len(file_friends_v2_accept_friend_request_rpc_proto_rawDesc)))
	})
	return file_friends_v2_accept_friend_request_rpc_proto_rawDescData
}

var file_friends_v2_accept_friend_request_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_friends_v2_accept_friend_request_rpc_proto_goTypes = []any{
	(*AcceptFriendRequestRequest)(nil),  // 0: friends.v2.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil), // 1: friends.v2.AcceptFriendRequestResponse
}
var file_friends_v2_accept_friend_request_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friends_v2_accept_friend_request_rpc_proto_init() }
func file_friends_v2_accept_friend_request_rpc_proto_init() {
	if File_friends_v2_accept_friend_request_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_v2_accept_friend_request_rpc_proto_rawDesc), len(file_friends_v2_accept_friend_request_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friends_v2_accept_friend_request_rpc_proto_goTypes,
		DependencyIndexes: file_friends_v2_accept_friend_request_rpc_proto_depIdxs,
		MessageInfos:      file_friends_v2_accept_friend_request_rpc_proto_msgTypes,
	}.Build()
	File_friends_v2_accept_friend_request_rpc_proto = out.File
	file_friends_v2_accept_friend_request_rpc_proto_goTypes = nil
	file_friends_v2_accept_friend_request_rpc_proto_depIdxs = nil
}
