// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: friends/v2/get_user_friend_data_wiiu_rpc.proto

package friendsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserFriendsDataWiiURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFriendsDataWiiURequest) Reset() {
	*x = GetUserFriendsDataWiiURequest{}
	mi := &file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFriendsDataWiiURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFriendsDataWiiURequest) ProtoMessage() {}

func (x *GetUserFriendsDataWiiURequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFriendsDataWiiURequest.ProtoReflect.Descriptor instead.
func (*GetUserFriendsDataWiiURequest) Descriptor() ([]byte, []int) {
	return file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserFriendsDataWiiURequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetUserFriendsDataWiiUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendInfoWiiU      `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFriendsDataWiiUResponse) Reset() {
	*x = GetUserFriendsDataWiiUResponse{}
	mi := &file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFriendsDataWiiUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFriendsDataWiiUResponse) ProtoMessage() {}

func (x *GetUserFriendsDataWiiUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFriendsDataWiiUResponse.ProtoReflect.Descriptor instead.
func (*GetUserFriendsDataWiiUResponse) Descriptor() ([]byte, []int) {
	return file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserFriendsDataWiiUResponse) GetFriends() []*FriendInfoWiiU {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_friends_v2_get_user_friend_data_wiiu_rpc_proto protoreflect.FileDescriptor

const file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDesc = "" +
	"\n" +
	".friends/v2/get_user_friend_data_wiiu_rpc.proto\x12\n" +
	"friends.v2\x1a\x1cfriends/v2/friend_info.proto\"1\n" +
	"\x1dGetUserFriendsDataWiiURequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"V\n" +
	"\x1eGetUserFriendsDataWiiUResponse\x124\n" +
	"\afriends\x18\x01 \x03(\v2\x1a.friends.v2.FriendInfoWiiUR\afriendsB\xb1\x01\n" +
	"\x0ecom.friends.v2B\x1dGetUserFriendDataWiiuRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/friends/v2;friendsv2\xa2\x02\x03FXX\xaa\x02\n" +
	"Friends.V2\xca\x02\n" +
	"Friends\\V2\xe2\x02\x16Friends\\V2\\GPBMetadata\xea\x02\vFriends::V2b\x06proto3"

var (
	file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescOnce sync.Once
	file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescData []byte
)

func file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescGZIP() []byte {
	file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescOnce.Do(func() {
		file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDesc), len(file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDesc)))
	})
	return file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDescData
}

var file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_friends_v2_get_user_friend_data_wiiu_rpc_proto_goTypes = []any{
	(*GetUserFriendsDataWiiURequest)(nil),  // 0: friends.v2.GetUserFriendsDataWiiURequest
	(*GetUserFriendsDataWiiUResponse)(nil), // 1: friends.v2.GetUserFriendsDataWiiUResponse
	(*FriendInfoWiiU)(nil),                 // 2: friends.v2.FriendInfoWiiU
}
var file_friends_v2_get_user_friend_data_wiiu_rpc_proto_depIdxs = []int32{
	2, // 0: friends.v2.GetUserFriendsDataWiiUResponse.friends:type_name -> friends.v2.FriendInfoWiiU
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_friends_v2_get_user_friend_data_wiiu_rpc_proto_init() }
func file_friends_v2_get_user_friend_data_wiiu_rpc_proto_init() {
	if File_friends_v2_get_user_friend_data_wiiu_rpc_proto != nil {
		return
	}
	file_friends_v2_friend_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDesc), len(file_friends_v2_get_user_friend_data_wiiu_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friends_v2_get_user_friend_data_wiiu_rpc_proto_goTypes,
		DependencyIndexes: file_friends_v2_get_user_friend_data_wiiu_rpc_proto_depIdxs,
		MessageInfos:      file_friends_v2_get_user_friend_data_wiiu_rpc_proto_msgTypes,
	}.Build()
	File_friends_v2_get_user_friend_data_wiiu_rpc_proto = out.File
	file_friends_v2_get_user_friend_data_wiiu_rpc_proto_goTypes = nil
	file_friends_v2_get_user_friend_data_wiiu_rpc_proto_depIdxs = nil
}
