// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: friends/v2/send_user_notification_wiiu_rpc.proto

package friendsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendUserNotificationWiiURequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pid              uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	NotificationData []byte                 `protobuf:"bytes,2,opt,name=notification_data,json=notificationData,proto3" json:"notification_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendUserNotificationWiiURequest) Reset() {
	*x = SendUserNotificationWiiURequest{}
	mi := &file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserNotificationWiiURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserNotificationWiiURequest) ProtoMessage() {}

func (x *SendUserNotificationWiiURequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserNotificationWiiURequest.ProtoReflect.Descriptor instead.
func (*SendUserNotificationWiiURequest) Descriptor() ([]byte, []int) {
	return file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SendUserNotificationWiiURequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SendUserNotificationWiiURequest) GetNotificationData() []byte {
	if x != nil {
		return x.NotificationData
	}
	return nil
}

type SendUserNotificationWiiUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserNotificationWiiUResponse) Reset() {
	*x = SendUserNotificationWiiUResponse{}
	mi := &file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserNotificationWiiUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserNotificationWiiUResponse) ProtoMessage() {}

func (x *SendUserNotificationWiiUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserNotificationWiiUResponse.ProtoReflect.Descriptor instead.
func (*SendUserNotificationWiiUResponse) Descriptor() ([]byte, []int) {
	return file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescGZIP(), []int{1}
}

var File_friends_v2_send_user_notification_wiiu_rpc_proto protoreflect.FileDescriptor

const file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDesc = "" +
	"\n" +
	"0friends/v2/send_user_notification_wiiu_rpc.proto\x12\n" +
	"friends.v2\"`\n" +
	"\x1fSendUserNotificationWiiURequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12+\n" +
	"\x11notification_data\x18\x02 \x01(\fR\x10notificationData\"\"\n" +
	" SendUserNotificationWiiUResponseB\xb4\x01\n" +
	"\x0ecom.friends.v2B SendUserNotificationWiiuRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/friends/v2;friendsv2\xa2\x02\x03FXX\xaa\x02\n" +
	"Friends.V2\xca\x02\n" +
	"Friends\\V2\xe2\x02\x16Friends\\V2\\GPBMetadata\xea\x02\vFriends::V2b\x06proto3"

var (
	file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescOnce sync.Once
	file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescData []byte
)

func file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescGZIP() []byte {
	file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescOnce.Do(func() {
		file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDesc), len(file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDesc)))
	})
	return file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDescData
}

var file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_friends_v2_send_user_notification_wiiu_rpc_proto_goTypes = []any{
	(*SendUserNotificationWiiURequest)(nil),  // 0: friends.v2.SendUserNotificationWiiURequest
	(*SendUserNotificationWiiUResponse)(nil), // 1: friends.v2.SendUserNotificationWiiUResponse
}
var file_friends_v2_send_user_notification_wiiu_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friends_v2_send_user_notification_wiiu_rpc_proto_init() }
func file_friends_v2_send_user_notification_wiiu_rpc_proto_init() {
	if File_friends_v2_send_user_notification_wiiu_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDesc), len(file_friends_v2_send_user_notification_wiiu_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friends_v2_send_user_notification_wiiu_rpc_proto_goTypes,
		DependencyIndexes: file_friends_v2_send_user_notification_wiiu_rpc_proto_depIdxs,
		MessageInfos:      file_friends_v2_send_user_notification_wiiu_rpc_proto_msgTypes,
	}.Build()
	File_friends_v2_send_user_notification_wiiu_rpc_proto = out.File
	file_friends_v2_send_user_notification_wiiu_rpc_proto_goTypes = nil
	file_friends_v2_send_user_notification_wiiu_rpc_proto_depIdxs = nil
}
