// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: miiverse/smm_request_post_id_rpc.proto

package miiverse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMMRequestPostIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      uint64                 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"` // TODO - Other course/user data?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMMRequestPostIDRequest) Reset() {
	*x = SMMRequestPostIDRequest{}
	mi := &file_miiverse_smm_request_post_id_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMMRequestPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMMRequestPostIDRequest) ProtoMessage() {}

func (x *SMMRequestPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_miiverse_smm_request_post_id_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMMRequestPostIDRequest.ProtoReflect.Descriptor instead.
func (*SMMRequestPostIDRequest) Descriptor() ([]byte, []int) {
	return file_miiverse_smm_request_post_id_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SMMRequestPostIDRequest) GetCourseId() uint64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type SMMRequestPostIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMMRequestPostIDResponse) Reset() {
	*x = SMMRequestPostIDResponse{}
	mi := &file_miiverse_smm_request_post_id_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMMRequestPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMMRequestPostIDResponse) ProtoMessage() {}

func (x *SMMRequestPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_miiverse_smm_request_post_id_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMMRequestPostIDResponse.ProtoReflect.Descriptor instead.
func (*SMMRequestPostIDResponse) Descriptor() ([]byte, []int) {
	return file_miiverse_smm_request_post_id_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SMMRequestPostIDResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_miiverse_smm_request_post_id_rpc_proto protoreflect.FileDescriptor

const file_miiverse_smm_request_post_id_rpc_proto_rawDesc = "" +
	"\n" +
	"&miiverse/smm_request_post_id_rpc.proto\x12\bmiiverse\"6\n" +
	"\x17SMMRequestPostIDRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x04R\bcourseId\"3\n" +
	"\x18SMMRequestPostIDResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postIdB\x95\x01\n" +
	"\fcom.miiverseB\x18SmmRequestPostIdRpcProtoP\x01Z+github.com/PretendoNetwork/grpc/go/miiverse\xa2\x02\x03MXX\xaa\x02\bMiiverse\xca\x02\bMiiverse\xe2\x02\x14Miiverse\\GPBMetadata\xea\x02\bMiiverseb\x06proto3"

var (
	file_miiverse_smm_request_post_id_rpc_proto_rawDescOnce sync.Once
	file_miiverse_smm_request_post_id_rpc_proto_rawDescData []byte
)

func file_miiverse_smm_request_post_id_rpc_proto_rawDescGZIP() []byte {
	file_miiverse_smm_request_post_id_rpc_proto_rawDescOnce.Do(func() {
		file_miiverse_smm_request_post_id_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_miiverse_smm_request_post_id_rpc_proto_rawDesc), len(file_miiverse_smm_request_post_id_rpc_proto_rawDesc)))
	})
	return file_miiverse_smm_request_post_id_rpc_proto_rawDescData
}

var file_miiverse_smm_request_post_id_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_miiverse_smm_request_post_id_rpc_proto_goTypes = []any{
	(*SMMRequestPostIDRequest)(nil),  // 0: miiverse.SMMRequestPostIDRequest
	(*SMMRequestPostIDResponse)(nil), // 1: miiverse.SMMRequestPostIDResponse
}
var file_miiverse_smm_request_post_id_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_miiverse_smm_request_post_id_rpc_proto_init() }
func file_miiverse_smm_request_post_id_rpc_proto_init() {
	if File_miiverse_smm_request_post_id_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_miiverse_smm_request_post_id_rpc_proto_rawDesc), len(file_miiverse_smm_request_post_id_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_miiverse_smm_request_post_id_rpc_proto_goTypes,
		DependencyIndexes: file_miiverse_smm_request_post_id_rpc_proto_depIdxs,
		MessageInfos:      file_miiverse_smm_request_post_id_rpc_proto_msgTypes,
	}.Build()
	File_miiverse_smm_request_post_id_rpc_proto = out.File
	file_miiverse_smm_request_post_id_rpc_proto_goTypes = nil
	file_miiverse_smm_request_post_id_rpc_proto_depIdxs = nil
}
