// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: api/v2/update_user_data_rpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Mii } from "./mii";
import { UserConnections } from "./user_connections";

export const protobufPackage = "api.v2";

export interface UpdateUserDataRequest {
  serverAccessLevel?: string | undefined;
  mii?: Mii | undefined;
  birthday?: string | undefined;
  gender?: string | undefined;
  country?: string | undefined;
  timezone?: string | undefined;
  language?: string | undefined;
  marketingFlag?: boolean | undefined;
}

export interface UpdateUserDataResponse {
  deleted: boolean;
  creationDate: string;
  updatedDate: string;
  pid: number;
  username: string;
  accessLevel: number;
  serverAccessLevel: string;
  mii: Mii | undefined;
  birthday: string;
  gender: string;
  country: string;
  timezone: string;
  language: string;
  emailAddress: string;
  connections: UserConnections | undefined;
  marketingFlag: boolean;
}

function createBaseUpdateUserDataRequest(): UpdateUserDataRequest {
  return {
    serverAccessLevel: undefined,
    mii: undefined,
    birthday: undefined,
    gender: undefined,
    country: undefined,
    timezone: undefined,
    language: undefined,
    marketingFlag: undefined,
  };
}

export const UpdateUserDataRequest: MessageFns<UpdateUserDataRequest> = {
  encode(message: UpdateUserDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverAccessLevel !== undefined) {
      writer.uint32(10).string(message.serverAccessLevel);
    }
    if (message.mii !== undefined) {
      Mii.encode(message.mii, writer.uint32(18).fork()).join();
    }
    if (message.birthday !== undefined) {
      writer.uint32(26).string(message.birthday);
    }
    if (message.gender !== undefined) {
      writer.uint32(34).string(message.gender);
    }
    if (message.country !== undefined) {
      writer.uint32(42).string(message.country);
    }
    if (message.timezone !== undefined) {
      writer.uint32(50).string(message.timezone);
    }
    if (message.language !== undefined) {
      writer.uint32(58).string(message.language);
    }
    if (message.marketingFlag !== undefined) {
      writer.uint32(64).bool(message.marketingFlag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverAccessLevel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mii = Mii.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.birthday = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.marketingFlag = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserDataRequest {
    return {
      serverAccessLevel: isSet(object.serverAccessLevel) ? globalThis.String(object.serverAccessLevel) : undefined,
      mii: isSet(object.mii) ? Mii.fromJSON(object.mii) : undefined,
      birthday: isSet(object.birthday) ? globalThis.String(object.birthday) : undefined,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : undefined,
      country: isSet(object.country) ? globalThis.String(object.country) : undefined,
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : undefined,
      language: isSet(object.language) ? globalThis.String(object.language) : undefined,
      marketingFlag: isSet(object.marketingFlag) ? globalThis.Boolean(object.marketingFlag) : undefined,
    };
  },

  toJSON(message: UpdateUserDataRequest): unknown {
    const obj: any = {};
    if (message.serverAccessLevel !== undefined) {
      obj.serverAccessLevel = message.serverAccessLevel;
    }
    if (message.mii !== undefined) {
      obj.mii = Mii.toJSON(message.mii);
    }
    if (message.birthday !== undefined) {
      obj.birthday = message.birthday;
    }
    if (message.gender !== undefined) {
      obj.gender = message.gender;
    }
    if (message.country !== undefined) {
      obj.country = message.country;
    }
    if (message.timezone !== undefined) {
      obj.timezone = message.timezone;
    }
    if (message.language !== undefined) {
      obj.language = message.language;
    }
    if (message.marketingFlag !== undefined) {
      obj.marketingFlag = message.marketingFlag;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateUserDataRequest>): UpdateUserDataRequest {
    return UpdateUserDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateUserDataRequest>): UpdateUserDataRequest {
    const message = createBaseUpdateUserDataRequest();
    message.serverAccessLevel = object.serverAccessLevel ?? undefined;
    message.mii = (object.mii !== undefined && object.mii !== null) ? Mii.fromPartial(object.mii) : undefined;
    message.birthday = object.birthday ?? undefined;
    message.gender = object.gender ?? undefined;
    message.country = object.country ?? undefined;
    message.timezone = object.timezone ?? undefined;
    message.language = object.language ?? undefined;
    message.marketingFlag = object.marketingFlag ?? undefined;
    return message;
  },
};

function createBaseUpdateUserDataResponse(): UpdateUserDataResponse {
  return {
    deleted: false,
    creationDate: "",
    updatedDate: "",
    pid: 0,
    username: "",
    accessLevel: 0,
    serverAccessLevel: "",
    mii: undefined,
    birthday: "",
    gender: "",
    country: "",
    timezone: "",
    language: "",
    emailAddress: "",
    connections: undefined,
    marketingFlag: false,
  };
}

export const UpdateUserDataResponse: MessageFns<UpdateUserDataResponse> = {
  encode(message: UpdateUserDataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deleted !== false) {
      writer.uint32(8).bool(message.deleted);
    }
    if (message.creationDate !== "") {
      writer.uint32(18).string(message.creationDate);
    }
    if (message.updatedDate !== "") {
      writer.uint32(26).string(message.updatedDate);
    }
    if (message.pid !== 0) {
      writer.uint32(32).uint32(message.pid);
    }
    if (message.username !== "") {
      writer.uint32(42).string(message.username);
    }
    if (message.accessLevel !== 0) {
      writer.uint32(48).int32(message.accessLevel);
    }
    if (message.serverAccessLevel !== "") {
      writer.uint32(58).string(message.serverAccessLevel);
    }
    if (message.mii !== undefined) {
      Mii.encode(message.mii, writer.uint32(66).fork()).join();
    }
    if (message.birthday !== "") {
      writer.uint32(74).string(message.birthday);
    }
    if (message.gender !== "") {
      writer.uint32(82).string(message.gender);
    }
    if (message.country !== "") {
      writer.uint32(90).string(message.country);
    }
    if (message.timezone !== "") {
      writer.uint32(98).string(message.timezone);
    }
    if (message.language !== "") {
      writer.uint32(106).string(message.language);
    }
    if (message.emailAddress !== "") {
      writer.uint32(114).string(message.emailAddress);
    }
    if (message.connections !== undefined) {
      UserConnections.encode(message.connections, writer.uint32(122).fork()).join();
    }
    if (message.marketingFlag !== false) {
      writer.uint32(128).bool(message.marketingFlag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deleted = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creationDate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedDate = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.pid = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.accessLevel = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.serverAccessLevel = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.mii = Mii.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.birthday = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.emailAddress = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.connections = UserConnections.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.marketingFlag = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserDataResponse {
    return {
      deleted: isSet(object.deleted) ? globalThis.Boolean(object.deleted) : false,
      creationDate: isSet(object.creationDate) ? globalThis.String(object.creationDate) : "",
      updatedDate: isSet(object.updatedDate) ? globalThis.String(object.updatedDate) : "",
      pid: isSet(object.pid) ? globalThis.Number(object.pid) : 0,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      accessLevel: isSet(object.accessLevel) ? globalThis.Number(object.accessLevel) : 0,
      serverAccessLevel: isSet(object.serverAccessLevel) ? globalThis.String(object.serverAccessLevel) : "",
      mii: isSet(object.mii) ? Mii.fromJSON(object.mii) : undefined,
      birthday: isSet(object.birthday) ? globalThis.String(object.birthday) : "",
      gender: isSet(object.gender) ? globalThis.String(object.gender) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      emailAddress: isSet(object.emailAddress) ? globalThis.String(object.emailAddress) : "",
      connections: isSet(object.connections) ? UserConnections.fromJSON(object.connections) : undefined,
      marketingFlag: isSet(object.marketingFlag) ? globalThis.Boolean(object.marketingFlag) : false,
    };
  },

  toJSON(message: UpdateUserDataResponse): unknown {
    const obj: any = {};
    if (message.deleted !== false) {
      obj.deleted = message.deleted;
    }
    if (message.creationDate !== "") {
      obj.creationDate = message.creationDate;
    }
    if (message.updatedDate !== "") {
      obj.updatedDate = message.updatedDate;
    }
    if (message.pid !== 0) {
      obj.pid = Math.round(message.pid);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.accessLevel !== 0) {
      obj.accessLevel = Math.round(message.accessLevel);
    }
    if (message.serverAccessLevel !== "") {
      obj.serverAccessLevel = message.serverAccessLevel;
    }
    if (message.mii !== undefined) {
      obj.mii = Mii.toJSON(message.mii);
    }
    if (message.birthday !== "") {
      obj.birthday = message.birthday;
    }
    if (message.gender !== "") {
      obj.gender = message.gender;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    if (message.timezone !== "") {
      obj.timezone = message.timezone;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.emailAddress !== "") {
      obj.emailAddress = message.emailAddress;
    }
    if (message.connections !== undefined) {
      obj.connections = UserConnections.toJSON(message.connections);
    }
    if (message.marketingFlag !== false) {
      obj.marketingFlag = message.marketingFlag;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateUserDataResponse>): UpdateUserDataResponse {
    return UpdateUserDataResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateUserDataResponse>): UpdateUserDataResponse {
    const message = createBaseUpdateUserDataResponse();
    message.deleted = object.deleted ?? false;
    message.creationDate = object.creationDate ?? "";
    message.updatedDate = object.updatedDate ?? "";
    message.pid = object.pid ?? 0;
    message.username = object.username ?? "";
    message.accessLevel = object.accessLevel ?? 0;
    message.serverAccessLevel = object.serverAccessLevel ?? "";
    message.mii = (object.mii !== undefined && object.mii !== null) ? Mii.fromPartial(object.mii) : undefined;
    message.birthday = object.birthday ?? "";
    message.gender = object.gender ?? "";
    message.country = object.country ?? "";
    message.timezone = object.timezone ?? "";
    message.language = object.language ?? "";
    message.emailAddress = object.emailAddress ?? "";
    message.connections = (object.connections !== undefined && object.connections !== null)
      ? UserConnections.fromPartial(object.connections)
      : undefined;
    message.marketingFlag = object.marketingFlag ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
