// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/v2/delete_account_rpc.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_api_v2_delete_account_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_delete_account_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_delete_account_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteAccountRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasDeleted    bool                   `protobuf:"varint,1,opt,name=has_deleted,json=hasDeleted,proto3" json:"has_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_api_v2_delete_account_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_delete_account_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_delete_account_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteAccountResponse) GetHasDeleted() bool {
	if x != nil {
		return x.HasDeleted
	}
	return false
}

var File_api_v2_delete_account_rpc_proto protoreflect.FileDescriptor

const file_api_v2_delete_account_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/v2/delete_account_rpc.proto\x12\x06api.v2\"(\n" +
	"\x14DeleteAccountRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"8\n" +
	"\x15DeleteAccountResponse\x12\x1f\n" +
	"\vhas_deleted\x18\x01 \x01(\bR\n" +
	"hasDeletedB\x8d\x01\n" +
	"\n" +
	"com.api.v2B\x15DeleteAccountRpcProtoP\x01Z/github.com/PretendoNetwork/grpc/go/api/v2;apiv2\xa2\x02\x03AXX\xaa\x02\x06Api.V2\xca\x02\x06Api\\V2\xe2\x02\x12Api\\V2\\GPBMetadata\xea\x02\aApi::V2b\x06proto3"

var (
	file_api_v2_delete_account_rpc_proto_rawDescOnce sync.Once
	file_api_v2_delete_account_rpc_proto_rawDescData []byte
)

func file_api_v2_delete_account_rpc_proto_rawDescGZIP() []byte {
	file_api_v2_delete_account_rpc_proto_rawDescOnce.Do(func() {
		file_api_v2_delete_account_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_delete_account_rpc_proto_rawDesc), len(file_api_v2_delete_account_rpc_proto_rawDesc)))
	})
	return file_api_v2_delete_account_rpc_proto_rawDescData
}

var file_api_v2_delete_account_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v2_delete_account_rpc_proto_goTypes = []any{
	(*DeleteAccountRequest)(nil),  // 0: api.v2.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 1: api.v2.DeleteAccountResponse
}
var file_api_v2_delete_account_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v2_delete_account_rpc_proto_init() }
func file_api_v2_delete_account_rpc_proto_init() {
	if File_api_v2_delete_account_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_delete_account_rpc_proto_rawDesc), len(file_api_v2_delete_account_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v2_delete_account_rpc_proto_goTypes,
		DependencyIndexes: file_api_v2_delete_account_rpc_proto_depIdxs,
		MessageInfos:      file_api_v2_delete_account_rpc_proto_msgTypes,
	}.Build()
	File_api_v2_delete_account_rpc_proto = out.File
	file_api_v2_delete_account_rpc_proto_goTypes = nil
	file_api_v2_delete_account_rpc_proto_depIdxs = nil
}
