// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/v2/forgot_password_rpc.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForgotPasswordRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EmailAddressOrUsername string                 `protobuf:"bytes,1,opt,name=email_address_or_username,json=emailAddressOrUsername,proto3" json:"email_address_or_username,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_api_v2_forgot_password_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_forgot_password_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_forgot_password_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ForgotPasswordRequest) GetEmailAddressOrUsername() string {
	if x != nil {
		return x.EmailAddressOrUsername
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_api_v2_forgot_password_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_forgot_password_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_forgot_password_rpc_proto_rawDescGZIP(), []int{1}
}

var File_api_v2_forgot_password_rpc_proto protoreflect.FileDescriptor

const file_api_v2_forgot_password_rpc_proto_rawDesc = "" +
	"\n" +
	" api/v2/forgot_password_rpc.proto\x12\x06api.v2\"R\n" +
	"\x15ForgotPasswordRequest\x129\n" +
	"\x19email_address_or_username\x18\x01 \x01(\tR\x16emailAddressOrUsername\"\x18\n" +
	"\x16ForgotPasswordResponseB\x8e\x01\n" +
	"\n" +
	"com.api.v2B\x16ForgotPasswordRpcProtoP\x01Z/github.com/PretendoNetwork/grpc/go/api/v2;apiv2\xa2\x02\x03AXX\xaa\x02\x06Api.V2\xca\x02\x06Api\\V2\xe2\x02\x12Api\\V2\\GPBMetadata\xea\x02\aApi::V2b\x06proto3"

var (
	file_api_v2_forgot_password_rpc_proto_rawDescOnce sync.Once
	file_api_v2_forgot_password_rpc_proto_rawDescData []byte
)

func file_api_v2_forgot_password_rpc_proto_rawDescGZIP() []byte {
	file_api_v2_forgot_password_rpc_proto_rawDescOnce.Do(func() {
		file_api_v2_forgot_password_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_forgot_password_rpc_proto_rawDesc), len(file_api_v2_forgot_password_rpc_proto_rawDesc)))
	})
	return file_api_v2_forgot_password_rpc_proto_rawDescData
}

var file_api_v2_forgot_password_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v2_forgot_password_rpc_proto_goTypes = []any{
	(*ForgotPasswordRequest)(nil),  // 0: api.v2.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil), // 1: api.v2.ForgotPasswordResponse
}
var file_api_v2_forgot_password_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v2_forgot_password_rpc_proto_init() }
func file_api_v2_forgot_password_rpc_proto_init() {
	if File_api_v2_forgot_password_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_forgot_password_rpc_proto_rawDesc), len(file_api_v2_forgot_password_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v2_forgot_password_rpc_proto_goTypes,
		DependencyIndexes: file_api_v2_forgot_password_rpc_proto_depIdxs,
		MessageInfos:      file_api_v2_forgot_password_rpc_proto_msgTypes,
	}.Build()
	File_api_v2_forgot_password_rpc_proto = out.File
	file_api_v2_forgot_password_rpc_proto_goTypes = nil
	file_api_v2_forgot_password_rpc_proto_depIdxs = nil
}
