// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/v2/get_user_data_rpc.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_api_v2_get_user_data_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_get_user_data_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_get_user_data_rpc_proto_rawDescGZIP(), []int{0}
}

type GetUserDataResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Deleted           bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreationDate      string                 `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	UpdatedDate       string                 `protobuf:"bytes,3,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Pid               uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Username          string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	AccessLevel       int32                  `protobuf:"varint,6,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	ServerAccessLevel string                 `protobuf:"bytes,7,opt,name=server_access_level,json=serverAccessLevel,proto3" json:"server_access_level,omitempty"`
	Mii               *Mii                   `protobuf:"bytes,8,opt,name=mii,proto3" json:"mii,omitempty"`
	Birthday          string                 `protobuf:"bytes,9,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender            string                 `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	Country           string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	Timezone          string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Language          string                 `protobuf:"bytes,13,opt,name=language,proto3" json:"language,omitempty"`
	EmailAddress      string                 `protobuf:"bytes,14,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Connections       *UserConnections       `protobuf:"bytes,15,opt,name=connections,proto3" json:"connections,omitempty"`
	MarketingFlag     bool                   `protobuf:"varint,16,opt,name=marketing_flag,json=marketingFlag,proto3" json:"marketing_flag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_api_v2_get_user_data_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_get_user_data_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_get_user_data_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserDataResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *GetUserDataResponse) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *GetUserDataResponse) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *GetUserDataResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GetUserDataResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserDataResponse) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

func (x *GetUserDataResponse) GetServerAccessLevel() string {
	if x != nil {
		return x.ServerAccessLevel
	}
	return ""
}

func (x *GetUserDataResponse) GetMii() *Mii {
	if x != nil {
		return x.Mii
	}
	return nil
}

func (x *GetUserDataResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *GetUserDataResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserDataResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetUserDataResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetUserDataResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetUserDataResponse) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *GetUserDataResponse) GetConnections() *UserConnections {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *GetUserDataResponse) GetMarketingFlag() bool {
	if x != nil {
		return x.MarketingFlag
	}
	return false
}

var File_api_v2_get_user_data_rpc_proto protoreflect.FileDescriptor

const file_api_v2_get_user_data_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/v2/get_user_data_rpc.proto\x12\x06api.v2\x1a\x10api/v2/mii.proto\x1a\x1dapi/v2/user_connections.proto\"\x14\n" +
	"\x12GetUserDataRequest\"\xa4\x04\n" +
	"\x13GetUserDataResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12#\n" +
	"\rcreation_date\x18\x02 \x01(\tR\fcreationDate\x12!\n" +
	"\fupdated_date\x18\x03 \x01(\tR\vupdatedDate\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12!\n" +
	"\faccess_level\x18\x06 \x01(\x05R\vaccessLevel\x12.\n" +
	"\x13server_access_level\x18\a \x01(\tR\x11serverAccessLevel\x12\x1d\n" +
	"\x03mii\x18\b \x01(\v2\v.api.v2.MiiR\x03mii\x12\x1a\n" +
	"\bbirthday\x18\t \x01(\tR\bbirthday\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\tR\x06gender\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x12\x1a\n" +
	"\blanguage\x18\r \x01(\tR\blanguage\x12#\n" +
	"\remail_address\x18\x0e \x01(\tR\femailAddress\x129\n" +
	"\vconnections\x18\x0f \x01(\v2\x17.api.v2.UserConnectionsR\vconnections\x12%\n" +
	"\x0emarketing_flag\x18\x10 \x01(\bR\rmarketingFlagB\x8b\x01\n" +
	"\n" +
	"com.api.v2B\x13GetUserDataRpcProtoP\x01Z/github.com/PretendoNetwork/grpc/go/api/v2;apiv2\xa2\x02\x03AXX\xaa\x02\x06Api.V2\xca\x02\x06Api\\V2\xe2\x02\x12Api\\V2\\GPBMetadata\xea\x02\aApi::V2b\x06proto3"

var (
	file_api_v2_get_user_data_rpc_proto_rawDescOnce sync.Once
	file_api_v2_get_user_data_rpc_proto_rawDescData []byte
)

func file_api_v2_get_user_data_rpc_proto_rawDescGZIP() []byte {
	file_api_v2_get_user_data_rpc_proto_rawDescOnce.Do(func() {
		file_api_v2_get_user_data_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_get_user_data_rpc_proto_rawDesc), len(file_api_v2_get_user_data_rpc_proto_rawDesc)))
	})
	return file_api_v2_get_user_data_rpc_proto_rawDescData
}

var file_api_v2_get_user_data_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v2_get_user_data_rpc_proto_goTypes = []any{
	(*GetUserDataRequest)(nil),  // 0: api.v2.GetUserDataRequest
	(*GetUserDataResponse)(nil), // 1: api.v2.GetUserDataResponse
	(*Mii)(nil),                 // 2: api.v2.Mii
	(*UserConnections)(nil),     // 3: api.v2.UserConnections
}
var file_api_v2_get_user_data_rpc_proto_depIdxs = []int32{
	2, // 0: api.v2.GetUserDataResponse.mii:type_name -> api.v2.Mii
	3, // 1: api.v2.GetUserDataResponse.connections:type_name -> api.v2.UserConnections
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v2_get_user_data_rpc_proto_init() }
func file_api_v2_get_user_data_rpc_proto_init() {
	if File_api_v2_get_user_data_rpc_proto != nil {
		return
	}
	file_api_v2_mii_proto_init()
	file_api_v2_user_connections_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_get_user_data_rpc_proto_rawDesc), len(file_api_v2_get_user_data_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v2_get_user_data_rpc_proto_goTypes,
		DependencyIndexes: file_api_v2_get_user_data_rpc_proto_depIdxs,
		MessageInfos:      file_api_v2_get_user_data_rpc_proto_msgTypes,
	}.Build()
	File_api_v2_get_user_data_rpc_proto = out.File
	file_api_v2_get_user_data_rpc_proto_goTypes = nil
	file_api_v2_get_user_data_rpc_proto_depIdxs = nil
}
