// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/v2/set_stripe_connection_data_rpc.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetStripeConnectionDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     *string                `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3,oneof" json:"customer_id,omitempty"`
	SubscriptionId *string                `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3,oneof" json:"subscription_id,omitempty"`
	PriceId        *string                `protobuf:"bytes,3,opt,name=price_id,json=priceId,proto3,oneof" json:"price_id,omitempty"`
	TierLevel      *uint32                `protobuf:"varint,4,opt,name=tier_level,json=tierLevel,proto3,oneof" json:"tier_level,omitempty"`
	TierName       *string                `protobuf:"bytes,5,opt,name=tier_name,json=tierName,proto3,oneof" json:"tier_name,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetStripeConnectionDataRequest) Reset() {
	*x = SetStripeConnectionDataRequest{}
	mi := &file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStripeConnectionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStripeConnectionDataRequest) ProtoMessage() {}

func (x *SetStripeConnectionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStripeConnectionDataRequest.ProtoReflect.Descriptor instead.
func (*SetStripeConnectionDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_set_stripe_connection_data_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SetStripeConnectionDataRequest) GetCustomerId() string {
	if x != nil && x.CustomerId != nil {
		return *x.CustomerId
	}
	return ""
}

func (x *SetStripeConnectionDataRequest) GetSubscriptionId() string {
	if x != nil && x.SubscriptionId != nil {
		return *x.SubscriptionId
	}
	return ""
}

func (x *SetStripeConnectionDataRequest) GetPriceId() string {
	if x != nil && x.PriceId != nil {
		return *x.PriceId
	}
	return ""
}

func (x *SetStripeConnectionDataRequest) GetTierLevel() uint32 {
	if x != nil && x.TierLevel != nil {
		return *x.TierLevel
	}
	return 0
}

func (x *SetStripeConnectionDataRequest) GetTierName() string {
	if x != nil && x.TierName != nil {
		return *x.TierName
	}
	return ""
}

func (x *SetStripeConnectionDataRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SetStripeConnectionDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStripeConnectionDataResponse) Reset() {
	*x = SetStripeConnectionDataResponse{}
	mi := &file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStripeConnectionDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStripeConnectionDataResponse) ProtoMessage() {}

func (x *SetStripeConnectionDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStripeConnectionDataResponse.ProtoReflect.Descriptor instead.
func (*SetStripeConnectionDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_set_stripe_connection_data_rpc_proto_rawDescGZIP(), []int{1}
}

var File_api_v2_set_stripe_connection_data_rpc_proto protoreflect.FileDescriptor

const file_api_v2_set_stripe_connection_data_rpc_proto_rawDesc = "" +
	"\n" +
	"+api/v2/set_stripe_connection_data_rpc.proto\x12\x06api.v2\"\xc6\x02\n" +
	"\x1eSetStripeConnectionDataRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tH\x00R\n" +
	"customerId\x88\x01\x01\x12,\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tH\x01R\x0esubscriptionId\x88\x01\x01\x12\x1e\n" +
	"\bprice_id\x18\x03 \x01(\tH\x02R\apriceId\x88\x01\x01\x12\"\n" +
	"\n" +
	"tier_level\x18\x04 \x01(\rH\x03R\ttierLevel\x88\x01\x01\x12 \n" +
	"\ttier_name\x18\x05 \x01(\tH\x04R\btierName\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestampB\x0e\n" +
	"\f_customer_idB\x12\n" +
	"\x10_subscription_idB\v\n" +
	"\t_price_idB\r\n" +
	"\v_tier_levelB\f\n" +
	"\n" +
	"_tier_name\"!\n" +
	"\x1fSetStripeConnectionDataResponseB\x97\x01\n" +
	"\n" +
	"com.api.v2B\x1fSetStripeConnectionDataRpcProtoP\x01Z/github.com/PretendoNetwork/grpc/go/api/v2;apiv2\xa2\x02\x03AXX\xaa\x02\x06Api.V2\xca\x02\x06Api\\V2\xe2\x02\x12Api\\V2\\GPBMetadata\xea\x02\aApi::V2b\x06proto3"

var (
	file_api_v2_set_stripe_connection_data_rpc_proto_rawDescOnce sync.Once
	file_api_v2_set_stripe_connection_data_rpc_proto_rawDescData []byte
)

func file_api_v2_set_stripe_connection_data_rpc_proto_rawDescGZIP() []byte {
	file_api_v2_set_stripe_connection_data_rpc_proto_rawDescOnce.Do(func() {
		file_api_v2_set_stripe_connection_data_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_set_stripe_connection_data_rpc_proto_rawDesc), len(file_api_v2_set_stripe_connection_data_rpc_proto_rawDesc)))
	})
	return file_api_v2_set_stripe_connection_data_rpc_proto_rawDescData
}

var file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v2_set_stripe_connection_data_rpc_proto_goTypes = []any{
	(*SetStripeConnectionDataRequest)(nil),  // 0: api.v2.SetStripeConnectionDataRequest
	(*SetStripeConnectionDataResponse)(nil), // 1: api.v2.SetStripeConnectionDataResponse
}
var file_api_v2_set_stripe_connection_data_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v2_set_stripe_connection_data_rpc_proto_init() }
func file_api_v2_set_stripe_connection_data_rpc_proto_init() {
	if File_api_v2_set_stripe_connection_data_rpc_proto != nil {
		return
	}
	file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_set_stripe_connection_data_rpc_proto_rawDesc), len(file_api_v2_set_stripe_connection_data_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v2_set_stripe_connection_data_rpc_proto_goTypes,
		DependencyIndexes: file_api_v2_set_stripe_connection_data_rpc_proto_depIdxs,
		MessageInfos:      file_api_v2_set_stripe_connection_data_rpc_proto_msgTypes,
	}.Build()
	File_api_v2_set_stripe_connection_data_rpc_proto = out.File
	file_api_v2_set_stripe_connection_data_rpc_proto_goTypes = nil
	file_api_v2_set_stripe_connection_data_rpc_proto_depIdxs = nil
}
