// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/v2/user_connections.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscordConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordConnection) Reset() {
	*x = DiscordConnection{}
	mi := &file_api_v2_user_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordConnection) ProtoMessage() {}

func (x *DiscordConnection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_user_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordConnection.ProtoReflect.Descriptor instead.
func (*DiscordConnection) Descriptor() ([]byte, []int) {
	return file_api_v2_user_connections_proto_rawDescGZIP(), []int{0}
}

func (x *DiscordConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StripeConnection struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CustomerId             *string                `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3,oneof" json:"customer_id,omitempty"`
	SubscriptionId         *string                `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3,oneof" json:"subscription_id,omitempty"`
	PriceId                *string                `protobuf:"bytes,3,opt,name=price_id,json=priceId,proto3,oneof" json:"price_id,omitempty"`
	TierLevel              *uint32                `protobuf:"varint,4,opt,name=tier_level,json=tierLevel,proto3,oneof" json:"tier_level,omitempty"`
	TierName               *string                `protobuf:"bytes,5,opt,name=tier_name,json=tierName,proto3,oneof" json:"tier_name,omitempty"`
	LatestWebhookTimestamp uint64                 `protobuf:"varint,6,opt,name=latest_webhook_timestamp,json=latestWebhookTimestamp,proto3" json:"latest_webhook_timestamp,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StripeConnection) Reset() {
	*x = StripeConnection{}
	mi := &file_api_v2_user_connections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripeConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripeConnection) ProtoMessage() {}

func (x *StripeConnection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_user_connections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripeConnection.ProtoReflect.Descriptor instead.
func (*StripeConnection) Descriptor() ([]byte, []int) {
	return file_api_v2_user_connections_proto_rawDescGZIP(), []int{1}
}

func (x *StripeConnection) GetCustomerId() string {
	if x != nil && x.CustomerId != nil {
		return *x.CustomerId
	}
	return ""
}

func (x *StripeConnection) GetSubscriptionId() string {
	if x != nil && x.SubscriptionId != nil {
		return *x.SubscriptionId
	}
	return ""
}

func (x *StripeConnection) GetPriceId() string {
	if x != nil && x.PriceId != nil {
		return *x.PriceId
	}
	return ""
}

func (x *StripeConnection) GetTierLevel() uint32 {
	if x != nil && x.TierLevel != nil {
		return *x.TierLevel
	}
	return 0
}

func (x *StripeConnection) GetTierName() string {
	if x != nil && x.TierName != nil {
		return *x.TierName
	}
	return ""
}

func (x *StripeConnection) GetLatestWebhookTimestamp() uint64 {
	if x != nil {
		return x.LatestWebhookTimestamp
	}
	return 0
}

type UserConnections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discord       *DiscordConnection     `protobuf:"bytes,1,opt,name=discord,proto3" json:"discord,omitempty"`
	Stripe        *StripeConnection      `protobuf:"bytes,2,opt,name=stripe,proto3" json:"stripe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnections) Reset() {
	*x = UserConnections{}
	mi := &file_api_v2_user_connections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnections) ProtoMessage() {}

func (x *UserConnections) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_user_connections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnections.ProtoReflect.Descriptor instead.
func (*UserConnections) Descriptor() ([]byte, []int) {
	return file_api_v2_user_connections_proto_rawDescGZIP(), []int{2}
}

func (x *UserConnections) GetDiscord() *DiscordConnection {
	if x != nil {
		return x.Discord
	}
	return nil
}

func (x *UserConnections) GetStripe() *StripeConnection {
	if x != nil {
		return x.Stripe
	}
	return nil
}

var File_api_v2_user_connections_proto protoreflect.FileDescriptor

const file_api_v2_user_connections_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/v2/user_connections.proto\x12\x06api.v2\"#\n" +
	"\x11DiscordConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd4\x02\n" +
	"\x10StripeConnection\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tH\x00R\n" +
	"customerId\x88\x01\x01\x12,\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tH\x01R\x0esubscriptionId\x88\x01\x01\x12\x1e\n" +
	"\bprice_id\x18\x03 \x01(\tH\x02R\apriceId\x88\x01\x01\x12\"\n" +
	"\n" +
	"tier_level\x18\x04 \x01(\rH\x03R\ttierLevel\x88\x01\x01\x12 \n" +
	"\ttier_name\x18\x05 \x01(\tH\x04R\btierName\x88\x01\x01\x128\n" +
	"\x18latest_webhook_timestamp\x18\x06 \x01(\x04R\x16latestWebhookTimestampB\x0e\n" +
	"\f_customer_idB\x12\n" +
	"\x10_subscription_idB\v\n" +
	"\t_price_idB\r\n" +
	"\v_tier_levelB\f\n" +
	"\n" +
	"_tier_name\"x\n" +
	"\x0fUserConnections\x123\n" +
	"\adiscord\x18\x01 \x01(\v2\x19.api.v2.DiscordConnectionR\adiscord\x120\n" +
	"\x06stripe\x18\x02 \x01(\v2\x18.api.v2.StripeConnectionR\x06stripeB\x8c\x01\n" +
	"\n" +
	"com.api.v2B\x14UserConnectionsProtoP\x01Z/github.com/PretendoNetwork/grpc/go/api/v2;apiv2\xa2\x02\x03AXX\xaa\x02\x06Api.V2\xca\x02\x06Api\\V2\xe2\x02\x12Api\\V2\\GPBMetadata\xea\x02\aApi::V2b\x06proto3"

var (
	file_api_v2_user_connections_proto_rawDescOnce sync.Once
	file_api_v2_user_connections_proto_rawDescData []byte
)

func file_api_v2_user_connections_proto_rawDescGZIP() []byte {
	file_api_v2_user_connections_proto_rawDescOnce.Do(func() {
		file_api_v2_user_connections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_user_connections_proto_rawDesc), len(file_api_v2_user_connections_proto_rawDesc)))
	})
	return file_api_v2_user_connections_proto_rawDescData
}

var file_api_v2_user_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v2_user_connections_proto_goTypes = []any{
	(*DiscordConnection)(nil), // 0: api.v2.DiscordConnection
	(*StripeConnection)(nil),  // 1: api.v2.StripeConnection
	(*UserConnections)(nil),   // 2: api.v2.UserConnections
}
var file_api_v2_user_connections_proto_depIdxs = []int32{
	0, // 0: api.v2.UserConnections.discord:type_name -> api.v2.DiscordConnection
	1, // 1: api.v2.UserConnections.stripe:type_name -> api.v2.StripeConnection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v2_user_connections_proto_init() }
func file_api_v2_user_connections_proto_init() {
	if File_api_v2_user_connections_proto != nil {
		return
	}
	file_api_v2_user_connections_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_user_connections_proto_rawDesc), len(file_api_v2_user_connections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v2_user_connections_proto_goTypes,
		DependencyIndexes: file_api_v2_user_connections_proto_depIdxs,
		MessageInfos:      file_api_v2_user_connections_proto_msgTypes,
	}.Build()
	File_api_v2_user_connections_proto = out.File
	file_api_v2_user_connections_proto_goTypes = nil
	file_api_v2_user_connections_proto_depIdxs = nil
}
