// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/account_service.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_v2_account_service_proto protoreflect.FileDescriptor

const file_account_v2_account_service_proto_rawDesc = "" +
	"\n" +
	" account/v2/account_service.proto\x12\n" +
	"account.v2\x1a-account/v2/create_audit_log_comment_rpc.proto\x1a'account/v2/create_ban_comment_rpc.proto\x1a\"account/v2/create_server_rpc.proto\x1a#account/v2/delete_account_rpc.proto\x1a account/v2/delete_pnid_rpc.proto\x1a\"account/v2/delete_server_rpc.proto\x1aEaccount/v2/exchange_independent_service_token_for_user_data_rpc.proto\x1a5account/v2/exchange_nex_token_for_user_data_rpc.proto\x1a7account/v2/exchange_oauth_token_for_user_data_rpc.proto\x1a@account/v2/exchange_password_reset_token_for_user_data_rpc.proto\x1a1account/v2/exchange_token_for_user_data_rpc.proto\x1a\x1caccount/v2/get_ban_rpc.proto\x1a\x1faccount/v2/get_device_rpc.proto\x1a$account/v2/get_nex_account_rpc.proto\x1a!account/v2/get_nex_data_rpc.proto\x1a%account/v2/get_nex_password_rpc.proto\x1a\x1daccount/v2/get_pnid_rpc.proto\x1a\x1eaccount/v2/get_pnids_rpc.proto\x1a\x1faccount/v2/get_server_rpc.proto\x1a\"account/v2/get_user_data_rpc.proto\x1a\x1eaccount/v2/issue_ban_rpc.proto\x1a,account/v2/list_audit_log_comments_rpc.proto\x1a$account/v2/list_audit_logs_rpc.proto\x1a&account/v2/list_ban_comments_rpc.proto\x1a\x1eaccount/v2/list_bans_rpc.proto\x1a!account/v2/list_devices_rpc.proto\x1a&account/v2/list_nex_accounts_rpc.proto\x1a\x1faccount/v2/list_pnids_rpc.proto\x1a!account/v2/list_servers_rpc.proto\x1a\x1faccount/v2/pardon_ban_rpc.proto\x1a\x1faccount/v2/update_ban_rpc.proto\x1a\"account/v2/update_device_rpc.proto\x1a'account/v2/update_nex_account_rpc.proto\x1a,account/v2/update_pnid_permissions_rpc.proto\x1a account/v2/update_pnid_rpc.proto\x1a\"account/v2/update_server_rpc.proto\x1a7account/v2/validate_independent_service_token_rpc.proto2\xc9\x1b\n" +
	"\x0eAccountService\x12S\n" +
	"\vGetUserData\x12\x1e.account.v2.GetUserDataRequest\x1a\x1f.account.v2.GetUserDataResponse\"\x03\x88\x02\x01\x12Y\n" +
	"\x0eGetNEXPassword\x12!.account.v2.GetNEXPasswordRequest\x1a\".account.v2.GetNEXPasswordResponse\"\x00\x12P\n" +
	"\n" +
	"GetNEXData\x12\x1d.account.v2.GetNEXDataRequest\x1a\x1e.account.v2.GetNEXDataResponse\"\x03\x88\x02\x01\x12q\n" +
	"\x15UpdatePNIDPermissions\x12(.account.v2.UpdatePNIDPermissionsRequest\x1a).account.v2.UpdatePNIDPermissionsResponse\"\x03\x88\x02\x01\x12z\n" +
	"\x18ExchangeTokenForUserData\x12+.account.v2.ExchangeTokenForUserDataRequest\x1a,.account.v2.ExchangeTokenForUserDataResponse\"\x03\x88\x02\x01\x12\x86\x01\n" +
	"\x1dExchangeOAuthTokenForUserData\x120.account.v2.ExchangeOAuthTokenForUserDataRequest\x1a1.account.v2.ExchangeOAuthTokenForUserDataResponse\"\x00\x12\x80\x01\n" +
	"\x1bExchangeNEXTokenForUserData\x12..account.v2.ExchangeNEXTokenForUserDataRequest\x1a/.account.v2.ExchangeNEXTokenForUserDataResponse\"\x00\x12\xad\x01\n" +
	"*ExchangeIndependentServiceTokenForUserData\x12=.account.v2.ExchangeIndependentServiceTokenForUserDataRequest\x1a>.account.v2.ExchangeIndependentServiceTokenForUserDataResponse\"\x00\x12\x9e\x01\n" +
	"%ExchangePasswordResetTokenForUserData\x128.account.v2.ExchangePasswordResetTokenForUserDataRequest\x1a9.account.v2.ExchangePasswordResetTokenForUserDataResponse\"\x00\x12\x8c\x01\n" +
	"\x1fValidateIndependentServiceToken\x122.account.v2.ValidateIndependentServiceTokenRequest\x1a3.account.v2.ValidateIndependentServiceTokenResponse\"\x00\x12Y\n" +
	"\rDeleteAccount\x12 .account.v2.DeleteAccountRequest\x1a!.account.v2.DeleteAccountResponse\"\x03\x88\x02\x01\x12P\n" +
	"\vListDevices\x12\x1e.account.v2.ListDevicesRequest\x1a\x1f.account.v2.ListDevicesResponse\"\x00\x12J\n" +
	"\tGetDevice\x12\x1c.account.v2.GetDeviceRequest\x1a\x1d.account.v2.GetDeviceResponse\"\x00\x12S\n" +
	"\fUpdateDevice\x12\x1f.account.v2.UpdateDeviceRequest\x1a .account.v2.UpdateDeviceResponse\"\x00\x12\\\n" +
	"\x0fListNEXAccounts\x12\".account.v2.ListNEXAccountsRequest\x1a#.account.v2.ListNEXAccountsResponse\"\x00\x12V\n" +
	"\rGetNEXAccount\x12 .account.v2.GetNEXAccountRequest\x1a!.account.v2.GetNEXAccountResponse\"\x00\x12_\n" +
	"\x10UpdateNEXAccount\x12#.account.v2.UpdateNEXAccountRequest\x1a$.account.v2.UpdateNEXAccountResponse\"\x00\x12P\n" +
	"\vListServers\x12\x1e.account.v2.ListServersRequest\x1a\x1f.account.v2.ListServersResponse\"\x00\x12S\n" +
	"\fCreateServer\x12\x1f.account.v2.CreateServerRequest\x1a .account.v2.CreateServerResponse\"\x00\x12J\n" +
	"\tGetServer\x12\x1c.account.v2.GetServerRequest\x1a\x1d.account.v2.GetServerResponse\"\x00\x12S\n" +
	"\fUpdateServer\x12\x1f.account.v2.UpdateServerRequest\x1a .account.v2.UpdateServerResponse\"\x00\x12S\n" +
	"\fDeleteServer\x12\x1f.account.v2.DeleteServerRequest\x1a .account.v2.DeleteServerResponse\"\x00\x12J\n" +
	"\tListPNIDs\x12\x1c.account.v2.ListPNIDsRequest\x1a\x1d.account.v2.ListPNIDsResponse\"\x00\x12D\n" +
	"\aGetPNID\x12\x1a.account.v2.GetPNIDRequest\x1a\x1b.account.v2.GetPNIDResponse\"\x00\x12G\n" +
	"\bGetPNIDs\x12\x1b.account.v2.GetPNIDsRequest\x1a\x1c.account.v2.GetPNIDsResponse\"\x00\x12M\n" +
	"\n" +
	"UpdatePNID\x12\x1d.account.v2.UpdatePNIDRequest\x1a\x1e.account.v2.UpdatePNIDResponse\"\x00\x12M\n" +
	"\n" +
	"DeletePNID\x12\x1d.account.v2.DeletePNIDRequest\x1a\x1e.account.v2.DeletePNIDResponse\"\x00\x12V\n" +
	"\rListAuditLogs\x12 .account.v2.ListAuditLogsRequest\x1a!.account.v2.ListAuditLogsResponse\"\x00\x12k\n" +
	"\x14ListAuditLogComments\x12'.account.v2.ListAuditLogCommentsRequest\x1a(.account.v2.ListAuditLogCommentsResponse\"\x00\x12n\n" +
	"\x15CreateAuditLogComment\x12(.account.v2.CreateAuditLogCommentRequest\x1a).account.v2.CreateAuditLogCommentResponse\"\x00\x12G\n" +
	"\bListBans\x12\x1b.account.v2.ListBansRequest\x1a\x1c.account.v2.ListBansResponse\"\x00\x12G\n" +
	"\bIssueBan\x12\x1b.account.v2.IssueBanRequest\x1a\x1c.account.v2.IssueBanResponse\"\x00\x12A\n" +
	"\x06GetBan\x12\x19.account.v2.GetBanRequest\x1a\x1a.account.v2.GetBanResponse\"\x00\x12J\n" +
	"\tUpdateBan\x12\x1c.account.v2.UpdateBanRequest\x1a\x1d.account.v2.UpdateBanResponse\"\x00\x12J\n" +
	"\tPardonBan\x12\x1c.account.v2.PardonBanRequest\x1a\x1d.account.v2.PardonBanResponse\"\x00\x12\\\n" +
	"\x0fListBanComments\x12\".account.v2.ListBanCommentsRequest\x1a#.account.v2.ListBanCommentsResponse\"\x00\x12_\n" +
	"\x10CreateBanComment\x12#.account.v2.CreateBanCommentRequest\x1a$.account.v2.CreateBanCommentResponse\"\x00B\xa7\x01\n" +
	"\x0ecom.account.v2B\x13AccountServiceProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var file_account_v2_account_service_proto_goTypes = []any{
	(*GetUserDataRequest)(nil),                                 // 0: account.v2.GetUserDataRequest
	(*GetNEXPasswordRequest)(nil),                              // 1: account.v2.GetNEXPasswordRequest
	(*GetNEXDataRequest)(nil),                                  // 2: account.v2.GetNEXDataRequest
	(*UpdatePNIDPermissionsRequest)(nil),                       // 3: account.v2.UpdatePNIDPermissionsRequest
	(*ExchangeTokenForUserDataRequest)(nil),                    // 4: account.v2.ExchangeTokenForUserDataRequest
	(*ExchangeOAuthTokenForUserDataRequest)(nil),               // 5: account.v2.ExchangeOAuthTokenForUserDataRequest
	(*ExchangeNEXTokenForUserDataRequest)(nil),                 // 6: account.v2.ExchangeNEXTokenForUserDataRequest
	(*ExchangeIndependentServiceTokenForUserDataRequest)(nil),  // 7: account.v2.ExchangeIndependentServiceTokenForUserDataRequest
	(*ExchangePasswordResetTokenForUserDataRequest)(nil),       // 8: account.v2.ExchangePasswordResetTokenForUserDataRequest
	(*ValidateIndependentServiceTokenRequest)(nil),             // 9: account.v2.ValidateIndependentServiceTokenRequest
	(*DeleteAccountRequest)(nil),                               // 10: account.v2.DeleteAccountRequest
	(*ListDevicesRequest)(nil),                                 // 11: account.v2.ListDevicesRequest
	(*GetDeviceRequest)(nil),                                   // 12: account.v2.GetDeviceRequest
	(*UpdateDeviceRequest)(nil),                                // 13: account.v2.UpdateDeviceRequest
	(*ListNEXAccountsRequest)(nil),                             // 14: account.v2.ListNEXAccountsRequest
	(*GetNEXAccountRequest)(nil),                               // 15: account.v2.GetNEXAccountRequest
	(*UpdateNEXAccountRequest)(nil),                            // 16: account.v2.UpdateNEXAccountRequest
	(*ListServersRequest)(nil),                                 // 17: account.v2.ListServersRequest
	(*CreateServerRequest)(nil),                                // 18: account.v2.CreateServerRequest
	(*GetServerRequest)(nil),                                   // 19: account.v2.GetServerRequest
	(*UpdateServerRequest)(nil),                                // 20: account.v2.UpdateServerRequest
	(*DeleteServerRequest)(nil),                                // 21: account.v2.DeleteServerRequest
	(*ListPNIDsRequest)(nil),                                   // 22: account.v2.ListPNIDsRequest
	(*GetPNIDRequest)(nil),                                     // 23: account.v2.GetPNIDRequest
	(*GetPNIDsRequest)(nil),                                    // 24: account.v2.GetPNIDsRequest
	(*UpdatePNIDRequest)(nil),                                  // 25: account.v2.UpdatePNIDRequest
	(*DeletePNIDRequest)(nil),                                  // 26: account.v2.DeletePNIDRequest
	(*ListAuditLogsRequest)(nil),                               // 27: account.v2.ListAuditLogsRequest
	(*ListAuditLogCommentsRequest)(nil),                        // 28: account.v2.ListAuditLogCommentsRequest
	(*CreateAuditLogCommentRequest)(nil),                       // 29: account.v2.CreateAuditLogCommentRequest
	(*ListBansRequest)(nil),                                    // 30: account.v2.ListBansRequest
	(*IssueBanRequest)(nil),                                    // 31: account.v2.IssueBanRequest
	(*GetBanRequest)(nil),                                      // 32: account.v2.GetBanRequest
	(*UpdateBanRequest)(nil),                                   // 33: account.v2.UpdateBanRequest
	(*PardonBanRequest)(nil),                                   // 34: account.v2.PardonBanRequest
	(*ListBanCommentsRequest)(nil),                             // 35: account.v2.ListBanCommentsRequest
	(*CreateBanCommentRequest)(nil),                            // 36: account.v2.CreateBanCommentRequest
	(*GetUserDataResponse)(nil),                                // 37: account.v2.GetUserDataResponse
	(*GetNEXPasswordResponse)(nil),                             // 38: account.v2.GetNEXPasswordResponse
	(*GetNEXDataResponse)(nil),                                 // 39: account.v2.GetNEXDataResponse
	(*UpdatePNIDPermissionsResponse)(nil),                      // 40: account.v2.UpdatePNIDPermissionsResponse
	(*ExchangeTokenForUserDataResponse)(nil),                   // 41: account.v2.ExchangeTokenForUserDataResponse
	(*ExchangeOAuthTokenForUserDataResponse)(nil),              // 42: account.v2.ExchangeOAuthTokenForUserDataResponse
	(*ExchangeNEXTokenForUserDataResponse)(nil),                // 43: account.v2.ExchangeNEXTokenForUserDataResponse
	(*ExchangeIndependentServiceTokenForUserDataResponse)(nil), // 44: account.v2.ExchangeIndependentServiceTokenForUserDataResponse
	(*ExchangePasswordResetTokenForUserDataResponse)(nil),      // 45: account.v2.ExchangePasswordResetTokenForUserDataResponse
	(*ValidateIndependentServiceTokenResponse)(nil),            // 46: account.v2.ValidateIndependentServiceTokenResponse
	(*DeleteAccountResponse)(nil),                              // 47: account.v2.DeleteAccountResponse
	(*ListDevicesResponse)(nil),                                // 48: account.v2.ListDevicesResponse
	(*GetDeviceResponse)(nil),                                  // 49: account.v2.GetDeviceResponse
	(*UpdateDeviceResponse)(nil),                               // 50: account.v2.UpdateDeviceResponse
	(*ListNEXAccountsResponse)(nil),                            // 51: account.v2.ListNEXAccountsResponse
	(*GetNEXAccountResponse)(nil),                              // 52: account.v2.GetNEXAccountResponse
	(*UpdateNEXAccountResponse)(nil),                           // 53: account.v2.UpdateNEXAccountResponse
	(*ListServersResponse)(nil),                                // 54: account.v2.ListServersResponse
	(*CreateServerResponse)(nil),                               // 55: account.v2.CreateServerResponse
	(*GetServerResponse)(nil),                                  // 56: account.v2.GetServerResponse
	(*UpdateServerResponse)(nil),                               // 57: account.v2.UpdateServerResponse
	(*DeleteServerResponse)(nil),                               // 58: account.v2.DeleteServerResponse
	(*ListPNIDsResponse)(nil),                                  // 59: account.v2.ListPNIDsResponse
	(*GetPNIDResponse)(nil),                                    // 60: account.v2.GetPNIDResponse
	(*GetPNIDsResponse)(nil),                                   // 61: account.v2.GetPNIDsResponse
	(*UpdatePNIDResponse)(nil),                                 // 62: account.v2.UpdatePNIDResponse
	(*DeletePNIDResponse)(nil),                                 // 63: account.v2.DeletePNIDResponse
	(*ListAuditLogsResponse)(nil),                              // 64: account.v2.ListAuditLogsResponse
	(*ListAuditLogCommentsResponse)(nil),                       // 65: account.v2.ListAuditLogCommentsResponse
	(*CreateAuditLogCommentResponse)(nil),                      // 66: account.v2.CreateAuditLogCommentResponse
	(*ListBansResponse)(nil),                                   // 67: account.v2.ListBansResponse
	(*IssueBanResponse)(nil),                                   // 68: account.v2.IssueBanResponse
	(*GetBanResponse)(nil),                                     // 69: account.v2.GetBanResponse
	(*UpdateBanResponse)(nil),                                  // 70: account.v2.UpdateBanResponse
	(*PardonBanResponse)(nil),                                  // 71: account.v2.PardonBanResponse
	(*ListBanCommentsResponse)(nil),                            // 72: account.v2.ListBanCommentsResponse
	(*CreateBanCommentResponse)(nil),                           // 73: account.v2.CreateBanCommentResponse
}
var file_account_v2_account_service_proto_depIdxs = []int32{
	0,  // 0: account.v2.AccountService.GetUserData:input_type -> account.v2.GetUserDataRequest
	1,  // 1: account.v2.AccountService.GetNEXPassword:input_type -> account.v2.GetNEXPasswordRequest
	2,  // 2: account.v2.AccountService.GetNEXData:input_type -> account.v2.GetNEXDataRequest
	3,  // 3: account.v2.AccountService.UpdatePNIDPermissions:input_type -> account.v2.UpdatePNIDPermissionsRequest
	4,  // 4: account.v2.AccountService.ExchangeTokenForUserData:input_type -> account.v2.ExchangeTokenForUserDataRequest
	5,  // 5: account.v2.AccountService.ExchangeOAuthTokenForUserData:input_type -> account.v2.ExchangeOAuthTokenForUserDataRequest
	6,  // 6: account.v2.AccountService.ExchangeNEXTokenForUserData:input_type -> account.v2.ExchangeNEXTokenForUserDataRequest
	7,  // 7: account.v2.AccountService.ExchangeIndependentServiceTokenForUserData:input_type -> account.v2.ExchangeIndependentServiceTokenForUserDataRequest
	8,  // 8: account.v2.AccountService.ExchangePasswordResetTokenForUserData:input_type -> account.v2.ExchangePasswordResetTokenForUserDataRequest
	9,  // 9: account.v2.AccountService.ValidateIndependentServiceToken:input_type -> account.v2.ValidateIndependentServiceTokenRequest
	10, // 10: account.v2.AccountService.DeleteAccount:input_type -> account.v2.DeleteAccountRequest
	11, // 11: account.v2.AccountService.ListDevices:input_type -> account.v2.ListDevicesRequest
	12, // 12: account.v2.AccountService.GetDevice:input_type -> account.v2.GetDeviceRequest
	13, // 13: account.v2.AccountService.UpdateDevice:input_type -> account.v2.UpdateDeviceRequest
	14, // 14: account.v2.AccountService.ListNEXAccounts:input_type -> account.v2.ListNEXAccountsRequest
	15, // 15: account.v2.AccountService.GetNEXAccount:input_type -> account.v2.GetNEXAccountRequest
	16, // 16: account.v2.AccountService.UpdateNEXAccount:input_type -> account.v2.UpdateNEXAccountRequest
	17, // 17: account.v2.AccountService.ListServers:input_type -> account.v2.ListServersRequest
	18, // 18: account.v2.AccountService.CreateServer:input_type -> account.v2.CreateServerRequest
	19, // 19: account.v2.AccountService.GetServer:input_type -> account.v2.GetServerRequest
	20, // 20: account.v2.AccountService.UpdateServer:input_type -> account.v2.UpdateServerRequest
	21, // 21: account.v2.AccountService.DeleteServer:input_type -> account.v2.DeleteServerRequest
	22, // 22: account.v2.AccountService.ListPNIDs:input_type -> account.v2.ListPNIDsRequest
	23, // 23: account.v2.AccountService.GetPNID:input_type -> account.v2.GetPNIDRequest
	24, // 24: account.v2.AccountService.GetPNIDs:input_type -> account.v2.GetPNIDsRequest
	25, // 25: account.v2.AccountService.UpdatePNID:input_type -> account.v2.UpdatePNIDRequest
	26, // 26: account.v2.AccountService.DeletePNID:input_type -> account.v2.DeletePNIDRequest
	27, // 27: account.v2.AccountService.ListAuditLogs:input_type -> account.v2.ListAuditLogsRequest
	28, // 28: account.v2.AccountService.ListAuditLogComments:input_type -> account.v2.ListAuditLogCommentsRequest
	29, // 29: account.v2.AccountService.CreateAuditLogComment:input_type -> account.v2.CreateAuditLogCommentRequest
	30, // 30: account.v2.AccountService.ListBans:input_type -> account.v2.ListBansRequest
	31, // 31: account.v2.AccountService.IssueBan:input_type -> account.v2.IssueBanRequest
	32, // 32: account.v2.AccountService.GetBan:input_type -> account.v2.GetBanRequest
	33, // 33: account.v2.AccountService.UpdateBan:input_type -> account.v2.UpdateBanRequest
	34, // 34: account.v2.AccountService.PardonBan:input_type -> account.v2.PardonBanRequest
	35, // 35: account.v2.AccountService.ListBanComments:input_type -> account.v2.ListBanCommentsRequest
	36, // 36: account.v2.AccountService.CreateBanComment:input_type -> account.v2.CreateBanCommentRequest
	37, // 37: account.v2.AccountService.GetUserData:output_type -> account.v2.GetUserDataResponse
	38, // 38: account.v2.AccountService.GetNEXPassword:output_type -> account.v2.GetNEXPasswordResponse
	39, // 39: account.v2.AccountService.GetNEXData:output_type -> account.v2.GetNEXDataResponse
	40, // 40: account.v2.AccountService.UpdatePNIDPermissions:output_type -> account.v2.UpdatePNIDPermissionsResponse
	41, // 41: account.v2.AccountService.ExchangeTokenForUserData:output_type -> account.v2.ExchangeTokenForUserDataResponse
	42, // 42: account.v2.AccountService.ExchangeOAuthTokenForUserData:output_type -> account.v2.ExchangeOAuthTokenForUserDataResponse
	43, // 43: account.v2.AccountService.ExchangeNEXTokenForUserData:output_type -> account.v2.ExchangeNEXTokenForUserDataResponse
	44, // 44: account.v2.AccountService.ExchangeIndependentServiceTokenForUserData:output_type -> account.v2.ExchangeIndependentServiceTokenForUserDataResponse
	45, // 45: account.v2.AccountService.ExchangePasswordResetTokenForUserData:output_type -> account.v2.ExchangePasswordResetTokenForUserDataResponse
	46, // 46: account.v2.AccountService.ValidateIndependentServiceToken:output_type -> account.v2.ValidateIndependentServiceTokenResponse
	47, // 47: account.v2.AccountService.DeleteAccount:output_type -> account.v2.DeleteAccountResponse
	48, // 48: account.v2.AccountService.ListDevices:output_type -> account.v2.ListDevicesResponse
	49, // 49: account.v2.AccountService.GetDevice:output_type -> account.v2.GetDeviceResponse
	50, // 50: account.v2.AccountService.UpdateDevice:output_type -> account.v2.UpdateDeviceResponse
	51, // 51: account.v2.AccountService.ListNEXAccounts:output_type -> account.v2.ListNEXAccountsResponse
	52, // 52: account.v2.AccountService.GetNEXAccount:output_type -> account.v2.GetNEXAccountResponse
	53, // 53: account.v2.AccountService.UpdateNEXAccount:output_type -> account.v2.UpdateNEXAccountResponse
	54, // 54: account.v2.AccountService.ListServers:output_type -> account.v2.ListServersResponse
	55, // 55: account.v2.AccountService.CreateServer:output_type -> account.v2.CreateServerResponse
	56, // 56: account.v2.AccountService.GetServer:output_type -> account.v2.GetServerResponse
	57, // 57: account.v2.AccountService.UpdateServer:output_type -> account.v2.UpdateServerResponse
	58, // 58: account.v2.AccountService.DeleteServer:output_type -> account.v2.DeleteServerResponse
	59, // 59: account.v2.AccountService.ListPNIDs:output_type -> account.v2.ListPNIDsResponse
	60, // 60: account.v2.AccountService.GetPNID:output_type -> account.v2.GetPNIDResponse
	61, // 61: account.v2.AccountService.GetPNIDs:output_type -> account.v2.GetPNIDsResponse
	62, // 62: account.v2.AccountService.UpdatePNID:output_type -> account.v2.UpdatePNIDResponse
	63, // 63: account.v2.AccountService.DeletePNID:output_type -> account.v2.DeletePNIDResponse
	64, // 64: account.v2.AccountService.ListAuditLogs:output_type -> account.v2.ListAuditLogsResponse
	65, // 65: account.v2.AccountService.ListAuditLogComments:output_type -> account.v2.ListAuditLogCommentsResponse
	66, // 66: account.v2.AccountService.CreateAuditLogComment:output_type -> account.v2.CreateAuditLogCommentResponse
	67, // 67: account.v2.AccountService.ListBans:output_type -> account.v2.ListBansResponse
	68, // 68: account.v2.AccountService.IssueBan:output_type -> account.v2.IssueBanResponse
	69, // 69: account.v2.AccountService.GetBan:output_type -> account.v2.GetBanResponse
	70, // 70: account.v2.AccountService.UpdateBan:output_type -> account.v2.UpdateBanResponse
	71, // 71: account.v2.AccountService.PardonBan:output_type -> account.v2.PardonBanResponse
	72, // 72: account.v2.AccountService.ListBanComments:output_type -> account.v2.ListBanCommentsResponse
	73, // 73: account.v2.AccountService.CreateBanComment:output_type -> account.v2.CreateBanCommentResponse
	37, // [37:74] is the sub-list for method output_type
	0,  // [0:37] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_account_v2_account_service_proto_init() }
func file_account_v2_account_service_proto_init() {
	if File_account_v2_account_service_proto != nil {
		return
	}
	file_account_v2_create_audit_log_comment_rpc_proto_init()
	file_account_v2_create_ban_comment_rpc_proto_init()
	file_account_v2_create_server_rpc_proto_init()
	file_account_v2_delete_account_rpc_proto_init()
	file_account_v2_delete_pnid_rpc_proto_init()
	file_account_v2_delete_server_rpc_proto_init()
	file_account_v2_exchange_independent_service_token_for_user_data_rpc_proto_init()
	file_account_v2_exchange_nex_token_for_user_data_rpc_proto_init()
	file_account_v2_exchange_oauth_token_for_user_data_rpc_proto_init()
	file_account_v2_exchange_password_reset_token_for_user_data_rpc_proto_init()
	file_account_v2_exchange_token_for_user_data_rpc_proto_init()
	file_account_v2_get_ban_rpc_proto_init()
	file_account_v2_get_device_rpc_proto_init()
	file_account_v2_get_nex_account_rpc_proto_init()
	file_account_v2_get_nex_data_rpc_proto_init()
	file_account_v2_get_nex_password_rpc_proto_init()
	file_account_v2_get_pnid_rpc_proto_init()
	file_account_v2_get_pnids_rpc_proto_init()
	file_account_v2_get_server_rpc_proto_init()
	file_account_v2_get_user_data_rpc_proto_init()
	file_account_v2_issue_ban_rpc_proto_init()
	file_account_v2_list_audit_log_comments_rpc_proto_init()
	file_account_v2_list_audit_logs_rpc_proto_init()
	file_account_v2_list_ban_comments_rpc_proto_init()
	file_account_v2_list_bans_rpc_proto_init()
	file_account_v2_list_devices_rpc_proto_init()
	file_account_v2_list_nex_accounts_rpc_proto_init()
	file_account_v2_list_pnids_rpc_proto_init()
	file_account_v2_list_servers_rpc_proto_init()
	file_account_v2_pardon_ban_rpc_proto_init()
	file_account_v2_update_ban_rpc_proto_init()
	file_account_v2_update_device_rpc_proto_init()
	file_account_v2_update_nex_account_rpc_proto_init()
	file_account_v2_update_pnid_permissions_rpc_proto_init()
	file_account_v2_update_pnid_rpc_proto_init()
	file_account_v2_update_server_rpc_proto_init()
	file_account_v2_validate_independent_service_token_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_account_service_proto_rawDesc), len(file_account_v2_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v2_account_service_proto_goTypes,
		DependencyIndexes: file_account_v2_account_service_proto_depIdxs,
	}.Build()
	File_account_v2_account_service_proto = out.File
	file_account_v2_account_service_proto_goTypes = nil
	file_account_v2_account_service_proto_depIdxs = nil
}
