// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/audit_log.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActionType       AuditLogActionType     `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=account.v2.AuditLogActionType" json:"action_type,omitempty"`
	ExecutedByPid    uint32                 `protobuf:"varint,3,opt,name=executed_by_pid,json=executedByPid,proto3" json:"executed_by_pid,omitempty"`
	CreatedTimestamp uint64                 `protobuf:"varint,4,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"`
	CommentCount     uint32                 `protobuf:"varint,5,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_account_v2_audit_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_audit_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_account_v2_audit_log_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetActionType() AuditLogActionType {
	if x != nil {
		return x.ActionType
	}
	return AuditLogActionType_AUDIT_LOG_ACTION_TYPE_UNSPECIFIED
}

func (x *AuditLog) GetExecutedByPid() uint32 {
	if x != nil {
		return x.ExecutedByPid
	}
	return 0
}

func (x *AuditLog) GetCreatedTimestamp() uint64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *AuditLog) GetCommentCount() uint32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *AuditLog) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

var File_account_v2_audit_log_proto protoreflect.FileDescriptor

const file_account_v2_audit_log_proto_rawDesc = "" +
	"\n" +
	"\x1aaccount/v2/audit_log.proto\x12\n" +
	"account.v2\x1a&account/v2/audit_log_action_type.proto\"\xfa\x01\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\vaction_type\x18\x02 \x01(\x0e2\x1e.account.v2.AuditLogActionTypeR\n" +
	"actionType\x12&\n" +
	"\x0fexecuted_by_pid\x18\x03 \x01(\rR\rexecutedByPid\x12+\n" +
	"\x11created_timestamp\x18\x04 \x01(\x04R\x10createdTimestamp\x12#\n" +
	"\rcomment_count\x18\x05 \x01(\rR\fcommentCount\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJsonB\xa1\x01\n" +
	"\x0ecom.account.v2B\rAuditLogProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_audit_log_proto_rawDescOnce sync.Once
	file_account_v2_audit_log_proto_rawDescData []byte
)

func file_account_v2_audit_log_proto_rawDescGZIP() []byte {
	file_account_v2_audit_log_proto_rawDescOnce.Do(func() {
		file_account_v2_audit_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_audit_log_proto_rawDesc), len(file_account_v2_audit_log_proto_rawDesc)))
	})
	return file_account_v2_audit_log_proto_rawDescData
}

var file_account_v2_audit_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_v2_audit_log_proto_goTypes = []any{
	(*AuditLog)(nil),        // 0: account.v2.AuditLog
	(AuditLogActionType)(0), // 1: account.v2.AuditLogActionType
}
var file_account_v2_audit_log_proto_depIdxs = []int32{
	1, // 0: account.v2.AuditLog.action_type:type_name -> account.v2.AuditLogActionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_v2_audit_log_proto_init() }
func file_account_v2_audit_log_proto_init() {
	if File_account_v2_audit_log_proto != nil {
		return
	}
	file_account_v2_audit_log_action_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_audit_log_proto_rawDesc), len(file_account_v2_audit_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_audit_log_proto_goTypes,
		DependencyIndexes: file_account_v2_audit_log_proto_depIdxs,
		MessageInfos:      file_account_v2_audit_log_proto_msgTypes,
	}.Build()
	File_account_v2_audit_log_proto = out.File
	file_account_v2_audit_log_proto_goTypes = nil
	file_account_v2_audit_log_proto_depIdxs = nil
}
