// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/create_audit_log_comment_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuditLogCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogCommentRequest) Reset() {
	*x = CreateAuditLogCommentRequest{}
	mi := &file_account_v2_create_audit_log_comment_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogCommentRequest) ProtoMessage() {}

func (x *CreateAuditLogCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_create_audit_log_comment_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateAuditLogCommentRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_create_audit_log_comment_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuditLogCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAuditLogCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateAuditLogCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Comment               `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogCommentResponse) Reset() {
	*x = CreateAuditLogCommentResponse{}
	mi := &file_account_v2_create_audit_log_comment_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogCommentResponse) ProtoMessage() {}

func (x *CreateAuditLogCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_create_audit_log_comment_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateAuditLogCommentResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_create_audit_log_comment_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuditLogCommentResponse) GetItem() *Comment {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_account_v2_create_audit_log_comment_rpc_proto protoreflect.FileDescriptor

const file_account_v2_create_audit_log_comment_rpc_proto_rawDesc = "" +
	"\n" +
	"-account/v2/create_audit_log_comment_rpc.proto\x12\n" +
	"account.v2\x1a\x18account/v2/comment.proto\"H\n" +
	"\x1cCreateAuditLogCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"H\n" +
	"\x1dCreateAuditLogCommentResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.account.v2.CommentR\x04itemB\xb1\x01\n" +
	"\x0ecom.account.v2B\x1dCreateAuditLogCommentRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_create_audit_log_comment_rpc_proto_rawDescOnce sync.Once
	file_account_v2_create_audit_log_comment_rpc_proto_rawDescData []byte
)

func file_account_v2_create_audit_log_comment_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_create_audit_log_comment_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_create_audit_log_comment_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_create_audit_log_comment_rpc_proto_rawDesc), len(file_account_v2_create_audit_log_comment_rpc_proto_rawDesc)))
	})
	return file_account_v2_create_audit_log_comment_rpc_proto_rawDescData
}

var file_account_v2_create_audit_log_comment_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_create_audit_log_comment_rpc_proto_goTypes = []any{
	(*CreateAuditLogCommentRequest)(nil),  // 0: account.v2.CreateAuditLogCommentRequest
	(*CreateAuditLogCommentResponse)(nil), // 1: account.v2.CreateAuditLogCommentResponse
	(*Comment)(nil),                       // 2: account.v2.Comment
}
var file_account_v2_create_audit_log_comment_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.CreateAuditLogCommentResponse.item:type_name -> account.v2.Comment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_v2_create_audit_log_comment_rpc_proto_init() }
func file_account_v2_create_audit_log_comment_rpc_proto_init() {
	if File_account_v2_create_audit_log_comment_rpc_proto != nil {
		return
	}
	file_account_v2_comment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_create_audit_log_comment_rpc_proto_rawDesc), len(file_account_v2_create_audit_log_comment_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_create_audit_log_comment_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_create_audit_log_comment_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_create_audit_log_comment_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_create_audit_log_comment_rpc_proto = out.File
	file_account_v2_create_audit_log_comment_rpc_proto_goTypes = nil
	file_account_v2_create_audit_log_comment_rpc_proto_depIdxs = nil
}
