// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/delete_pnid_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletePNIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePNIDRequest) Reset() {
	*x = DeletePNIDRequest{}
	mi := &file_account_v2_delete_pnid_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePNIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePNIDRequest) ProtoMessage() {}

func (x *DeletePNIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_delete_pnid_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePNIDRequest.ProtoReflect.Descriptor instead.
func (*DeletePNIDRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_delete_pnid_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *DeletePNIDRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type DeletePNIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePNIDResponse) Reset() {
	*x = DeletePNIDResponse{}
	mi := &file_account_v2_delete_pnid_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePNIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePNIDResponse) ProtoMessage() {}

func (x *DeletePNIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_delete_pnid_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePNIDResponse.ProtoReflect.Descriptor instead.
func (*DeletePNIDResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_delete_pnid_rpc_proto_rawDescGZIP(), []int{1}
}

var File_account_v2_delete_pnid_rpc_proto protoreflect.FileDescriptor

const file_account_v2_delete_pnid_rpc_proto_rawDesc = "" +
	"\n" +
	" account/v2/delete_pnid_rpc.proto\x12\n" +
	"account.v2\"%\n" +
	"\x11DeletePNIDRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"\x14\n" +
	"\x12DeletePNIDResponseB\xa6\x01\n" +
	"\x0ecom.account.v2B\x12DeletePnidRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_delete_pnid_rpc_proto_rawDescOnce sync.Once
	file_account_v2_delete_pnid_rpc_proto_rawDescData []byte
)

func file_account_v2_delete_pnid_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_delete_pnid_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_delete_pnid_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_delete_pnid_rpc_proto_rawDesc), len(file_account_v2_delete_pnid_rpc_proto_rawDesc)))
	})
	return file_account_v2_delete_pnid_rpc_proto_rawDescData
}

var file_account_v2_delete_pnid_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_delete_pnid_rpc_proto_goTypes = []any{
	(*DeletePNIDRequest)(nil),  // 0: account.v2.DeletePNIDRequest
	(*DeletePNIDResponse)(nil), // 1: account.v2.DeletePNIDResponse
}
var file_account_v2_delete_pnid_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v2_delete_pnid_rpc_proto_init() }
func file_account_v2_delete_pnid_rpc_proto_init() {
	if File_account_v2_delete_pnid_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_delete_pnid_rpc_proto_rawDesc), len(file_account_v2_delete_pnid_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_delete_pnid_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_delete_pnid_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_delete_pnid_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_delete_pnid_rpc_proto = out.File
	file_account_v2_delete_pnid_rpc_proto_goTypes = nil
	file_account_v2_delete_pnid_rpc_proto_depIdxs = nil
}
