// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/get_pnids_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPNIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           []uint32               `protobuf:"varint,1,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPNIDsRequest) Reset() {
	*x = GetPNIDsRequest{}
	mi := &file_account_v2_get_pnids_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPNIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPNIDsRequest) ProtoMessage() {}

func (x *GetPNIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_pnids_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPNIDsRequest.ProtoReflect.Descriptor instead.
func (*GetPNIDsRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_get_pnids_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetPNIDsRequest) GetPid() []uint32 {
	if x != nil {
		return x.Pid
	}
	return nil
}

type GetPNIDsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserData      map[uint32]*GetPNIDResponse `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPNIDsResponse) Reset() {
	*x = GetPNIDsResponse{}
	mi := &file_account_v2_get_pnids_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPNIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPNIDsResponse) ProtoMessage() {}

func (x *GetPNIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_pnids_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPNIDsResponse.ProtoReflect.Descriptor instead.
func (*GetPNIDsResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_get_pnids_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetPNIDsResponse) GetUserData() map[uint32]*GetPNIDResponse {
	if x != nil {
		return x.UserData
	}
	return nil
}

var File_account_v2_get_pnids_rpc_proto protoreflect.FileDescriptor

const file_account_v2_get_pnids_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1eaccount/v2/get_pnids_rpc.proto\x12\n" +
	"account.v2\x1a\x1daccount/v2/get_pnid_rpc.proto\"#\n" +
	"\x0fGetPNIDsRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x03(\rR\x03pid\"\xb5\x01\n" +
	"\x10GetPNIDsResponse\x12G\n" +
	"\tuser_data\x18\x01 \x03(\v2*.account.v2.GetPNIDsResponse.UserDataEntryR\buserData\x1aX\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.account.v2.GetPNIDResponseR\x05value:\x028\x01B\xa4\x01\n" +
	"\x0ecom.account.v2B\x10GetPnidsRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_get_pnids_rpc_proto_rawDescOnce sync.Once
	file_account_v2_get_pnids_rpc_proto_rawDescData []byte
)

func file_account_v2_get_pnids_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_get_pnids_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_get_pnids_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_get_pnids_rpc_proto_rawDesc), len(file_account_v2_get_pnids_rpc_proto_rawDesc)))
	})
	return file_account_v2_get_pnids_rpc_proto_rawDescData
}

var file_account_v2_get_pnids_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_v2_get_pnids_rpc_proto_goTypes = []any{
	(*GetPNIDsRequest)(nil),  // 0: account.v2.GetPNIDsRequest
	(*GetPNIDsResponse)(nil), // 1: account.v2.GetPNIDsResponse
	nil,                      // 2: account.v2.GetPNIDsResponse.UserDataEntry
	(*GetPNIDResponse)(nil),  // 3: account.v2.GetPNIDResponse
}
var file_account_v2_get_pnids_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.GetPNIDsResponse.user_data:type_name -> account.v2.GetPNIDsResponse.UserDataEntry
	3, // 1: account.v2.GetPNIDsResponse.UserDataEntry.value:type_name -> account.v2.GetPNIDResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_v2_get_pnids_rpc_proto_init() }
func file_account_v2_get_pnids_rpc_proto_init() {
	if File_account_v2_get_pnids_rpc_proto != nil {
		return
	}
	file_account_v2_get_pnid_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_get_pnids_rpc_proto_rawDesc), len(file_account_v2_get_pnids_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_get_pnids_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_get_pnids_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_get_pnids_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_get_pnids_rpc_proto = out.File
	file_account_v2_get_pnids_rpc_proto_goTypes = nil
	file_account_v2_get_pnids_rpc_proto_depIdxs = nil
}
