// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/get_server_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_account_v2_get_server_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_server_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_get_server_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_account_v2_get_server_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_server_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_get_server_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_account_v2_get_server_rpc_proto protoreflect.FileDescriptor

const file_account_v2_get_server_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1faccount/v2/get_server_rpc.proto\x12\n" +
	"account.v2\x1a\x17account/v2/server.proto\"\"\n" +
	"\x10GetServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.account.v2.ServerR\x06serverB\xa5\x01\n" +
	"\x0ecom.account.v2B\x11GetServerRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_get_server_rpc_proto_rawDescOnce sync.Once
	file_account_v2_get_server_rpc_proto_rawDescData []byte
)

func file_account_v2_get_server_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_get_server_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_get_server_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_get_server_rpc_proto_rawDesc), len(file_account_v2_get_server_rpc_proto_rawDesc)))
	})
	return file_account_v2_get_server_rpc_proto_rawDescData
}

var file_account_v2_get_server_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_get_server_rpc_proto_goTypes = []any{
	(*GetServerRequest)(nil),  // 0: account.v2.GetServerRequest
	(*GetServerResponse)(nil), // 1: account.v2.GetServerResponse
	(*Server)(nil),            // 2: account.v2.Server
}
var file_account_v2_get_server_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.GetServerResponse.server:type_name -> account.v2.Server
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_v2_get_server_rpc_proto_init() }
func file_account_v2_get_server_rpc_proto_init() {
	if File_account_v2_get_server_rpc_proto != nil {
		return
	}
	file_account_v2_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_get_server_rpc_proto_rawDesc), len(file_account_v2_get_server_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_get_server_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_get_server_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_get_server_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_get_server_rpc_proto = out.File
	file_account_v2_get_server_rpc_proto_goTypes = nil
	file_account_v2_get_server_rpc_proto_depIdxs = nil
}
