// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/get_pnid_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPNIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPNIDRequest) Reset() {
	*x = GetPNIDRequest{}
	mi := &file_account_v2_get_pnid_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPNIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPNIDRequest) ProtoMessage() {}

func (x *GetPNIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_pnid_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPNIDRequest.ProtoReflect.Descriptor instead.
func (*GetPNIDRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_get_pnid_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetPNIDRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetPNIDResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Deleted           bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Pid               uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AccessLevel       int32                  `protobuf:"varint,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	ServerAccessLevel string                 `protobuf:"bytes,5,opt,name=server_access_level,json=serverAccessLevel,proto3" json:"server_access_level,omitempty"`
	Mii               *Mii                   `protobuf:"bytes,6,opt,name=mii,proto3" json:"mii,omitempty"`
	CreationDate      string                 `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Birthdate         string                 `protobuf:"bytes,8,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Gender            string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Country           string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Language          string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	EmailAddress      string                 `protobuf:"bytes,12,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	TierName          string                 `protobuf:"bytes,13,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	Permissions       *PNIDPermissionFlags   `protobuf:"bytes,14,opt,name=permissions,proto3" json:"permissions,omitempty"`
	LinkedDevices     []*Device              `protobuf:"bytes,15,rep,name=linked_devices,json=linkedDevices,proto3" json:"linked_devices,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPNIDResponse) Reset() {
	*x = GetPNIDResponse{}
	mi := &file_account_v2_get_pnid_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPNIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPNIDResponse) ProtoMessage() {}

func (x *GetPNIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_get_pnid_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPNIDResponse.ProtoReflect.Descriptor instead.
func (*GetPNIDResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_get_pnid_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetPNIDResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *GetPNIDResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GetPNIDResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetPNIDResponse) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

func (x *GetPNIDResponse) GetServerAccessLevel() string {
	if x != nil {
		return x.ServerAccessLevel
	}
	return ""
}

func (x *GetPNIDResponse) GetMii() *Mii {
	if x != nil {
		return x.Mii
	}
	return nil
}

func (x *GetPNIDResponse) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *GetPNIDResponse) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *GetPNIDResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetPNIDResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetPNIDResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetPNIDResponse) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *GetPNIDResponse) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *GetPNIDResponse) GetPermissions() *PNIDPermissionFlags {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetPNIDResponse) GetLinkedDevices() []*Device {
	if x != nil {
		return x.LinkedDevices
	}
	return nil
}

var File_account_v2_get_pnid_rpc_proto protoreflect.FileDescriptor

const file_account_v2_get_pnid_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/v2/get_pnid_rpc.proto\x12\n" +
	"account.v2\x1a\x17account/v2/device.proto\x1a\x14account/v2/mii.proto\x1a&account/v2/pnid_permission_flags.proto\"\"\n" +
	"\x0eGetPNIDRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"\xa0\x04\n" +
	"\x0fGetPNIDResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\faccess_level\x18\x04 \x01(\x05R\vaccessLevel\x12.\n" +
	"\x13server_access_level\x18\x05 \x01(\tR\x11serverAccessLevel\x12!\n" +
	"\x03mii\x18\x06 \x01(\v2\x0f.account.v2.MiiR\x03mii\x12#\n" +
	"\rcreation_date\x18\a \x01(\tR\fcreationDate\x12\x1c\n" +
	"\tbirthdate\x18\b \x01(\tR\tbirthdate\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x12#\n" +
	"\remail_address\x18\f \x01(\tR\femailAddress\x12\x1b\n" +
	"\ttier_name\x18\r \x01(\tR\btierName\x12A\n" +
	"\vpermissions\x18\x0e \x01(\v2\x1f.account.v2.PNIDPermissionFlagsR\vpermissions\x129\n" +
	"\x0elinked_devices\x18\x0f \x03(\v2\x12.account.v2.DeviceR\rlinkedDevicesB\xa3\x01\n" +
	"\x0ecom.account.v2B\x0fGetPnidRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_get_pnid_rpc_proto_rawDescOnce sync.Once
	file_account_v2_get_pnid_rpc_proto_rawDescData []byte
)

func file_account_v2_get_pnid_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_get_pnid_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_get_pnid_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_get_pnid_rpc_proto_rawDesc), len(file_account_v2_get_pnid_rpc_proto_rawDesc)))
	})
	return file_account_v2_get_pnid_rpc_proto_rawDescData
}

var file_account_v2_get_pnid_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_get_pnid_rpc_proto_goTypes = []any{
	(*GetPNIDRequest)(nil),      // 0: account.v2.GetPNIDRequest
	(*GetPNIDResponse)(nil),     // 1: account.v2.GetPNIDResponse
	(*Mii)(nil),                 // 2: account.v2.Mii
	(*PNIDPermissionFlags)(nil), // 3: account.v2.PNIDPermissionFlags
	(*Device)(nil),              // 4: account.v2.Device
}
var file_account_v2_get_pnid_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.GetPNIDResponse.mii:type_name -> account.v2.Mii
	3, // 1: account.v2.GetPNIDResponse.permissions:type_name -> account.v2.PNIDPermissionFlags
	4, // 2: account.v2.GetPNIDResponse.linked_devices:type_name -> account.v2.Device
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_account_v2_get_pnid_rpc_proto_init() }
func file_account_v2_get_pnid_rpc_proto_init() {
	if File_account_v2_get_pnid_rpc_proto != nil {
		return
	}
	file_account_v2_device_proto_init()
	file_account_v2_mii_proto_init()
	file_account_v2_pnid_permission_flags_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_get_pnid_rpc_proto_rawDesc), len(file_account_v2_get_pnid_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_get_pnid_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_get_pnid_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_get_pnid_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_get_pnid_rpc_proto = out.File
	file_account_v2_get_pnid_rpc_proto_goTypes = nil
	file_account_v2_get_pnid_rpc_proto_depIdxs = nil
}
