// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/list_audit_logs_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAuditLogsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Page          *PageInput                   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Filter        *ListAuditLogsRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_list_audit_logs_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditLogsRequest) GetPage() *PageInput {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListAuditLogsRequest) GetFilter() *ListAuditLogsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResults           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Items         []*AuditLog            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_list_audit_logs_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditLogsResponse) GetPage() *PageResults {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListAuditLogsResponse) GetItems() []*AuditLog {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAuditLogsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutedByPid []uint32               `protobuf:"varint,1,rep,packed,name=executed_by_pid,json=executedByPid,proto3" json:"executed_by_pid,omitempty"`
	ActionType    []AuditLogActionType   `protobuf:"varint,2,rep,packed,name=action_type,json=actionType,proto3,enum=account.v2.AuditLogActionType" json:"action_type,omitempty"`
	ExtraJson     *string                `protobuf:"bytes,3,opt,name=extra_json,json=extraJson,proto3,oneof" json:"extra_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest_Filter) Reset() {
	*x = ListAuditLogsRequest_Filter{}
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest_Filter) ProtoMessage() {}

func (x *ListAuditLogsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_list_audit_logs_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_account_v2_list_audit_logs_rpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListAuditLogsRequest_Filter) GetExecutedByPid() []uint32 {
	if x != nil {
		return x.ExecutedByPid
	}
	return nil
}

func (x *ListAuditLogsRequest_Filter) GetActionType() []AuditLogActionType {
	if x != nil {
		return x.ActionType
	}
	return nil
}

func (x *ListAuditLogsRequest_Filter) GetExtraJson() string {
	if x != nil && x.ExtraJson != nil {
		return *x.ExtraJson
	}
	return ""
}

var File_account_v2_list_audit_logs_rpc_proto protoreflect.FileDescriptor

const file_account_v2_list_audit_logs_rpc_proto_rawDesc = "" +
	"\n" +
	"$account/v2/list_audit_logs_rpc.proto\x12\n" +
	"account.v2\x1a\x1aaccount/v2/audit_log.proto\x1a&account/v2/audit_log_action_type.proto\x1a\x15account/v2/page.proto\"\xa9\x02\n" +
	"\x14ListAuditLogsRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.account.v2.PageInputR\x04page\x12?\n" +
	"\x06filter\x18\x02 \x01(\v2'.account.v2.ListAuditLogsRequest.FilterR\x06filter\x1a\xa4\x01\n" +
	"\x06Filter\x12&\n" +
	"\x0fexecuted_by_pid\x18\x01 \x03(\rR\rexecutedByPid\x12?\n" +
	"\vaction_type\x18\x02 \x03(\x0e2\x1e.account.v2.AuditLogActionTypeR\n" +
	"actionType\x12\"\n" +
	"\n" +
	"extra_json\x18\x03 \x01(\tH\x00R\textraJson\x88\x01\x01B\r\n" +
	"\v_extra_json\"p\n" +
	"\x15ListAuditLogsResponse\x12+\n" +
	"\x04page\x18\x01 \x01(\v2\x17.account.v2.PageResultsR\x04page\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.account.v2.AuditLogR\x05itemsB\xa9\x01\n" +
	"\x0ecom.account.v2B\x15ListAuditLogsRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_list_audit_logs_rpc_proto_rawDescOnce sync.Once
	file_account_v2_list_audit_logs_rpc_proto_rawDescData []byte
)

func file_account_v2_list_audit_logs_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_list_audit_logs_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_list_audit_logs_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_list_audit_logs_rpc_proto_rawDesc), len(file_account_v2_list_audit_logs_rpc_proto_rawDesc)))
	})
	return file_account_v2_list_audit_logs_rpc_proto_rawDescData
}

var file_account_v2_list_audit_logs_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_v2_list_audit_logs_rpc_proto_goTypes = []any{
	(*ListAuditLogsRequest)(nil),        // 0: account.v2.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil),       // 1: account.v2.ListAuditLogsResponse
	(*ListAuditLogsRequest_Filter)(nil), // 2: account.v2.ListAuditLogsRequest.Filter
	(*PageInput)(nil),                   // 3: account.v2.PageInput
	(*PageResults)(nil),                 // 4: account.v2.PageResults
	(*AuditLog)(nil),                    // 5: account.v2.AuditLog
	(AuditLogActionType)(0),             // 6: account.v2.AuditLogActionType
}
var file_account_v2_list_audit_logs_rpc_proto_depIdxs = []int32{
	3, // 0: account.v2.ListAuditLogsRequest.page:type_name -> account.v2.PageInput
	2, // 1: account.v2.ListAuditLogsRequest.filter:type_name -> account.v2.ListAuditLogsRequest.Filter
	4, // 2: account.v2.ListAuditLogsResponse.page:type_name -> account.v2.PageResults
	5, // 3: account.v2.ListAuditLogsResponse.items:type_name -> account.v2.AuditLog
	6, // 4: account.v2.ListAuditLogsRequest.Filter.action_type:type_name -> account.v2.AuditLogActionType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_account_v2_list_audit_logs_rpc_proto_init() }
func file_account_v2_list_audit_logs_rpc_proto_init() {
	if File_account_v2_list_audit_logs_rpc_proto != nil {
		return
	}
	file_account_v2_audit_log_proto_init()
	file_account_v2_audit_log_action_type_proto_init()
	file_account_v2_page_proto_init()
	file_account_v2_list_audit_logs_rpc_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_list_audit_logs_rpc_proto_rawDesc), len(file_account_v2_list_audit_logs_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_list_audit_logs_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_list_audit_logs_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_list_audit_logs_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_list_audit_logs_rpc_proto = out.File
	file_account_v2_list_audit_logs_rpc_proto_goTypes = nil
	file_account_v2_list_audit_logs_rpc_proto_depIdxs = nil
}
