// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/page.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInput) Reset() {
	*x = PageInput{}
	mi := &file_account_v2_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInput) ProtoMessage() {}

func (x *PageInput) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInput.ProtoReflect.Descriptor instead.
func (*PageInput) Descriptor() ([]byte, []int) {
	return file_account_v2_page_proto_rawDescGZIP(), []int{0}
}

func (x *PageInput) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageInput) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PageResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ItemCount     uint32                 `protobuf:"varint,3,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResults) Reset() {
	*x = PageResults{}
	mi := &file_account_v2_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResults) ProtoMessage() {}

func (x *PageResults) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResults.ProtoReflect.Descriptor instead.
func (*PageResults) Descriptor() ([]byte, []int) {
	return file_account_v2_page_proto_rawDescGZIP(), []int{1}
}

func (x *PageResults) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResults) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PageResults) GetItemCount() uint32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

var File_account_v2_page_proto protoreflect.FileDescriptor

const file_account_v2_page_proto_rawDesc = "" +
	"\n" +
	"\x15account/v2/page.proto\x12\n" +
	"account.v2\"9\n" +
	"\tPageInput\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"Z\n" +
	"\vPageResults\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x1d\n" +
	"\n" +
	"item_count\x18\x03 \x01(\rR\titemCountB\x9d\x01\n" +
	"\x0ecom.account.v2B\tPageProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_page_proto_rawDescOnce sync.Once
	file_account_v2_page_proto_rawDescData []byte
)

func file_account_v2_page_proto_rawDescGZIP() []byte {
	file_account_v2_page_proto_rawDescOnce.Do(func() {
		file_account_v2_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_page_proto_rawDesc), len(file_account_v2_page_proto_rawDesc)))
	})
	return file_account_v2_page_proto_rawDescData
}

var file_account_v2_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_page_proto_goTypes = []any{
	(*PageInput)(nil),   // 0: account.v2.PageInput
	(*PageResults)(nil), // 1: account.v2.PageResults
}
var file_account_v2_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v2_page_proto_init() }
func file_account_v2_page_proto_init() {
	if File_account_v2_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_page_proto_rawDesc), len(file_account_v2_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_page_proto_goTypes,
		DependencyIndexes: file_account_v2_page_proto_depIdxs,
		MessageInfos:      file_account_v2_page_proto_msgTypes,
	}.Build()
	File_account_v2_page_proto = out.File
	file_account_v2_page_proto_goTypes = nil
	file_account_v2_page_proto_depIdxs = nil
}
