// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/token_info.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO - Move this to own file
type SystemType int32

const (
	SystemType_SYSTEM_TYPE_UNSPECIFIED    SystemType = 0
	SystemType_SYSTEM_TYPE_WUP            SystemType = 1
	SystemType_SYSTEM_TYPE_CTR            SystemType = 2
	SystemType_SYSTEM_TYPE_API            SystemType = 3
	SystemType_SYSTEM_TYPE_PASSWORD_RESET SystemType = 255
)

// Enum value maps for SystemType.
var (
	SystemType_name = map[int32]string{
		0:   "SYSTEM_TYPE_UNSPECIFIED",
		1:   "SYSTEM_TYPE_WUP",
		2:   "SYSTEM_TYPE_CTR",
		3:   "SYSTEM_TYPE_API",
		255: "SYSTEM_TYPE_PASSWORD_RESET",
	}
	SystemType_value = map[string]int32{
		"SYSTEM_TYPE_UNSPECIFIED":    0,
		"SYSTEM_TYPE_WUP":            1,
		"SYSTEM_TYPE_CTR":            2,
		"SYSTEM_TYPE_API":            3,
		"SYSTEM_TYPE_PASSWORD_RESET": 255,
	}
)

func (x SystemType) Enum() *SystemType {
	p := new(SystemType)
	*p = x
	return p
}

func (x SystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v2_token_info_proto_enumTypes[0].Descriptor()
}

func (SystemType) Type() protoreflect.EnumType {
	return &file_account_v2_token_info_proto_enumTypes[0]
}

func (x SystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemType.Descriptor instead.
func (SystemType) EnumDescriptor() ([]byte, []int) {
	return file_account_v2_token_info_proto_rawDescGZIP(), []int{0}
}

// TODO - Move this to own file
type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED         TokenType = 0
	TokenType_TOKEN_TYPE_OAUTH_ACCESS        TokenType = 1
	TokenType_TOKEN_TYPE_OAUTH_REFRESH       TokenType = 2
	TokenType_TOKEN_TYPE_NEX                 TokenType = 3
	TokenType_TOKEN_TYPE_INDEPENDENT_SERVICE TokenType = 4
	TokenType_TOKEN_TYPE_PASSWORD_RESET      TokenType = 5
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "TOKEN_TYPE_OAUTH_ACCESS",
		2: "TOKEN_TYPE_OAUTH_REFRESH",
		3: "TOKEN_TYPE_NEX",
		4: "TOKEN_TYPE_INDEPENDENT_SERVICE",
		5: "TOKEN_TYPE_PASSWORD_RESET",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED":         0,
		"TOKEN_TYPE_OAUTH_ACCESS":        1,
		"TOKEN_TYPE_OAUTH_REFRESH":       2,
		"TOKEN_TYPE_NEX":                 3,
		"TOKEN_TYPE_INDEPENDENT_SERVICE": 4,
		"TOKEN_TYPE_PASSWORD_RESET":      5,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v2_token_info_proto_enumTypes[1].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_account_v2_token_info_proto_enumTypes[1]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_account_v2_token_info_proto_rawDescGZIP(), []int{1}
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=account.v2.SystemType" json:"system_type,omitempty"`
	TokenType     TokenType              `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=account.v2.TokenType" json:"token_type,omitempty"`
	Pid           uint64                 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	AccessLevel   int32                  `protobuf:"varint,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	TitleId       uint64                 `protobuf:"varint,5,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	IssueTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issue_time,json=issueTime,proto3" json:"issue_time,omitempty"`
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_account_v2_token_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_token_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_account_v2_token_info_proto_rawDescGZIP(), []int{0}
}

func (x *TokenInfo) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNSPECIFIED
}

func (x *TokenInfo) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_UNSPECIFIED
}

func (x *TokenInfo) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TokenInfo) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

func (x *TokenInfo) GetTitleId() uint64 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *TokenInfo) GetIssueTime() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueTime
	}
	return nil
}

func (x *TokenInfo) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_account_v2_token_info_proto protoreflect.FileDescriptor

const file_account_v2_token_info_proto_rawDesc = "" +
	"\n" +
	"\x1baccount/v2/token_info.proto\x12\n" +
	"account.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\tTokenInfo\x127\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x16.account.v2.SystemTypeR\n" +
	"systemType\x124\n" +
	"\n" +
	"token_type\x18\x02 \x01(\x0e2\x15.account.v2.TokenTypeR\ttokenType\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x04R\x03pid\x12!\n" +
	"\faccess_level\x18\x04 \x01(\x05R\vaccessLevel\x12\x19\n" +
	"\btitle_id\x18\x05 \x01(\x04R\atitleId\x129\n" +
	"\n" +
	"issue_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tissueTime\x12;\n" +
	"\vexpire_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime*\x89\x01\n" +
	"\n" +
	"SystemType\x12\x1b\n" +
	"\x17SYSTEM_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSYSTEM_TYPE_WUP\x10\x01\x12\x13\n" +
	"\x0fSYSTEM_TYPE_CTR\x10\x02\x12\x13\n" +
	"\x0fSYSTEM_TYPE_API\x10\x03\x12\x1f\n" +
	"\x1aSYSTEM_TYPE_PASSWORD_RESET\x10\xff\x01*\xb9\x01\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOKEN_TYPE_OAUTH_ACCESS\x10\x01\x12\x1c\n" +
	"\x18TOKEN_TYPE_OAUTH_REFRESH\x10\x02\x12\x12\n" +
	"\x0eTOKEN_TYPE_NEX\x10\x03\x12\"\n" +
	"\x1eTOKEN_TYPE_INDEPENDENT_SERVICE\x10\x04\x12\x1d\n" +
	"\x19TOKEN_TYPE_PASSWORD_RESET\x10\x05B\xa2\x01\n" +
	"\x0ecom.account.v2B\x0eTokenInfoProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_token_info_proto_rawDescOnce sync.Once
	file_account_v2_token_info_proto_rawDescData []byte
)

func file_account_v2_token_info_proto_rawDescGZIP() []byte {
	file_account_v2_token_info_proto_rawDescOnce.Do(func() {
		file_account_v2_token_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_token_info_proto_rawDesc), len(file_account_v2_token_info_proto_rawDesc)))
	})
	return file_account_v2_token_info_proto_rawDescData
}

var file_account_v2_token_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_account_v2_token_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_v2_token_info_proto_goTypes = []any{
	(SystemType)(0),               // 0: account.v2.SystemType
	(TokenType)(0),                // 1: account.v2.TokenType
	(*TokenInfo)(nil),             // 2: account.v2.TokenInfo
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_account_v2_token_info_proto_depIdxs = []int32{
	0, // 0: account.v2.TokenInfo.system_type:type_name -> account.v2.SystemType
	1, // 1: account.v2.TokenInfo.token_type:type_name -> account.v2.TokenType
	3, // 2: account.v2.TokenInfo.issue_time:type_name -> google.protobuf.Timestamp
	3, // 3: account.v2.TokenInfo.expire_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_account_v2_token_info_proto_init() }
func file_account_v2_token_info_proto_init() {
	if File_account_v2_token_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_token_info_proto_rawDesc), len(file_account_v2_token_info_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_token_info_proto_goTypes,
		DependencyIndexes: file_account_v2_token_info_proto_depIdxs,
		EnumInfos:         file_account_v2_token_info_proto_enumTypes,
		MessageInfos:      file_account_v2_token_info_proto_msgTypes,
	}.Build()
	File_account_v2_token_info_proto = out.File
	file_account_v2_token_info_proto_goTypes = nil
	file_account_v2_token_info_proto_depIdxs = nil
}
