// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/update_server_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateServerRequest struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	Id              string                                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip              *string                               `protobuf:"bytes,2,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Port            *uint32                               `protobuf:"varint,3,opt,name=port,proto3,oneof" json:"port,omitempty"`
	ServiceName     *string                               `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	ServiceType     *string                               `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3,oneof" json:"service_type,omitempty"`
	GameServerId    *string                               `protobuf:"bytes,6,opt,name=game_server_id,json=gameServerId,proto3,oneof" json:"game_server_id,omitempty"`
	TitleIds        *UpdateServerRequest_UpdateStringList `protobuf:"bytes,7,opt,name=title_ids,json=titleIds,proto3,oneof" json:"title_ids,omitempty"`
	AccessMode      *string                               `protobuf:"bytes,8,opt,name=access_mode,json=accessMode,proto3,oneof" json:"access_mode,omitempty"`
	MaintenanceMode *bool                                 `protobuf:"varint,9,opt,name=maintenance_mode,json=maintenanceMode,proto3,oneof" json:"maintenance_mode,omitempty"`
	Device          *uint32                               `protobuf:"varint,10,opt,name=device,proto3,oneof" json:"device,omitempty"`
	AesKey          *string                               `protobuf:"bytes,11,opt,name=aes_key,json=aesKey,proto3,oneof" json:"aes_key,omitempty"`
	ClientId        *UpdateServerRequest_NullableString   `protobuf:"bytes,12,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_update_server_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServerRequest) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *UpdateServerRequest) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *UpdateServerRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *UpdateServerRequest) GetServiceType() string {
	if x != nil && x.ServiceType != nil {
		return *x.ServiceType
	}
	return ""
}

func (x *UpdateServerRequest) GetGameServerId() string {
	if x != nil && x.GameServerId != nil {
		return *x.GameServerId
	}
	return ""
}

func (x *UpdateServerRequest) GetTitleIds() *UpdateServerRequest_UpdateStringList {
	if x != nil {
		return x.TitleIds
	}
	return nil
}

func (x *UpdateServerRequest) GetAccessMode() string {
	if x != nil && x.AccessMode != nil {
		return *x.AccessMode
	}
	return ""
}

func (x *UpdateServerRequest) GetMaintenanceMode() bool {
	if x != nil && x.MaintenanceMode != nil {
		return *x.MaintenanceMode
	}
	return false
}

func (x *UpdateServerRequest) GetDevice() uint32 {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return 0
}

func (x *UpdateServerRequest) GetAesKey() string {
	if x != nil && x.AesKey != nil {
		return *x.AesKey
	}
	return ""
}

func (x *UpdateServerRequest) GetClientId() *UpdateServerRequest_NullableString {
	if x != nil {
		return x.ClientId
	}
	return nil
}

type UpdateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerResponse) Reset() {
	*x = UpdateServerResponse{}
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerResponse) ProtoMessage() {}

func (x *UpdateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_update_server_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UpdateServerRequest_NullableString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest_NullableString) Reset() {
	*x = UpdateServerRequest_NullableString{}
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest_NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest_NullableString) ProtoMessage() {}

func (x *UpdateServerRequest_NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest_NullableString.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest_NullableString) Descriptor() ([]byte, []int) {
	return file_account_v2_update_server_rpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdateServerRequest_NullableString) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type UpdateServerRequest_UpdateStringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []string               `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest_UpdateStringList) Reset() {
	*x = UpdateServerRequest_UpdateStringList{}
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest_UpdateStringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest_UpdateStringList) ProtoMessage() {}

func (x *UpdateServerRequest_UpdateStringList) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_server_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest_UpdateStringList.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest_UpdateStringList) Descriptor() ([]byte, []int) {
	return file_account_v2_update_server_rpc_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UpdateServerRequest_UpdateStringList) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateServerRequest_UpdateStringList) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

var File_account_v2_update_server_rpc_proto protoreflect.FileDescriptor

const file_account_v2_update_server_rpc_proto_rawDesc = "" +
	"\n" +
	"\"account/v2/update_server_rpc.proto\x12\n" +
	"account.v2\x1a\x17account/v2/server.proto\"\x97\x06\n" +
	"\x13UpdateServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x02ip\x18\x02 \x01(\tH\x00R\x02ip\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x03 \x01(\rH\x01R\x04port\x88\x01\x01\x12&\n" +
	"\fservice_name\x18\x04 \x01(\tH\x02R\vserviceName\x88\x01\x01\x12&\n" +
	"\fservice_type\x18\x05 \x01(\tH\x03R\vserviceType\x88\x01\x01\x12)\n" +
	"\x0egame_server_id\x18\x06 \x01(\tH\x04R\fgameServerId\x88\x01\x01\x12R\n" +
	"\ttitle_ids\x18\a \x01(\v20.account.v2.UpdateServerRequest.UpdateStringListH\x05R\btitleIds\x88\x01\x01\x12$\n" +
	"\vaccess_mode\x18\b \x01(\tH\x06R\n" +
	"accessMode\x88\x01\x01\x12.\n" +
	"\x10maintenance_mode\x18\t \x01(\bH\aR\x0fmaintenanceMode\x88\x01\x01\x12\x1b\n" +
	"\x06device\x18\n" +
	" \x01(\rH\bR\x06device\x88\x01\x01\x12\x1c\n" +
	"\aaes_key\x18\v \x01(\tH\tR\x06aesKey\x88\x01\x01\x12P\n" +
	"\tclient_id\x18\f \x01(\v2..account.v2.UpdateServerRequest.NullableStringH\n" +
	"R\bclientId\x88\x01\x01\x1a5\n" +
	"\x0eNullableString\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\x1a<\n" +
	"\x10UpdateStringList\x12\x10\n" +
	"\x03add\x18\x01 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x02 \x03(\tR\x06removeB\x05\n" +
	"\x03_ipB\a\n" +
	"\x05_portB\x0f\n" +
	"\r_service_nameB\x0f\n" +
	"\r_service_typeB\x11\n" +
	"\x0f_game_server_idB\f\n" +
	"\n" +
	"_title_idsB\x0e\n" +
	"\f_access_modeB\x13\n" +
	"\x11_maintenance_modeB\t\n" +
	"\a_deviceB\n" +
	"\n" +
	"\b_aes_keyB\f\n" +
	"\n" +
	"_client_id\"B\n" +
	"\x14UpdateServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.account.v2.ServerR\x06serverB\xa8\x01\n" +
	"\x0ecom.account.v2B\x14UpdateServerRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_update_server_rpc_proto_rawDescOnce sync.Once
	file_account_v2_update_server_rpc_proto_rawDescData []byte
)

func file_account_v2_update_server_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_update_server_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_update_server_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_update_server_rpc_proto_rawDesc), len(file_account_v2_update_server_rpc_proto_rawDesc)))
	})
	return file_account_v2_update_server_rpc_proto_rawDescData
}

var file_account_v2_update_server_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_v2_update_server_rpc_proto_goTypes = []any{
	(*UpdateServerRequest)(nil),                  // 0: account.v2.UpdateServerRequest
	(*UpdateServerResponse)(nil),                 // 1: account.v2.UpdateServerResponse
	(*UpdateServerRequest_NullableString)(nil),   // 2: account.v2.UpdateServerRequest.NullableString
	(*UpdateServerRequest_UpdateStringList)(nil), // 3: account.v2.UpdateServerRequest.UpdateStringList
	(*Server)(nil),                               // 4: account.v2.Server
}
var file_account_v2_update_server_rpc_proto_depIdxs = []int32{
	3, // 0: account.v2.UpdateServerRequest.title_ids:type_name -> account.v2.UpdateServerRequest.UpdateStringList
	2, // 1: account.v2.UpdateServerRequest.client_id:type_name -> account.v2.UpdateServerRequest.NullableString
	4, // 2: account.v2.UpdateServerResponse.server:type_name -> account.v2.Server
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_account_v2_update_server_rpc_proto_init() }
func file_account_v2_update_server_rpc_proto_init() {
	if File_account_v2_update_server_rpc_proto != nil {
		return
	}
	file_account_v2_server_proto_init()
	file_account_v2_update_server_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_account_v2_update_server_rpc_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_update_server_rpc_proto_rawDesc), len(file_account_v2_update_server_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_update_server_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_update_server_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_update_server_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_update_server_rpc_proto = out.File
	file_account_v2_update_server_rpc_proto_goTypes = nil
	file_account_v2_update_server_rpc_proto_depIdxs = nil
}
