// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/update_nex_account_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateNEXAccountRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Pid               uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ServerAccessLevel *string                `protobuf:"bytes,2,opt,name=server_access_level,json=serverAccessLevel,proto3,oneof" json:"server_access_level,omitempty"`
	AccessLevel       *int32                 `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,oneof" json:"access_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateNEXAccountRequest) Reset() {
	*x = UpdateNEXAccountRequest{}
	mi := &file_account_v2_update_nex_account_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNEXAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNEXAccountRequest) ProtoMessage() {}

func (x *UpdateNEXAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_nex_account_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNEXAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateNEXAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_update_nex_account_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateNEXAccountRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdateNEXAccountRequest) GetServerAccessLevel() string {
	if x != nil && x.ServerAccessLevel != nil {
		return *x.ServerAccessLevel
	}
	return ""
}

func (x *UpdateNEXAccountRequest) GetAccessLevel() int32 {
	if x != nil && x.AccessLevel != nil {
		return *x.AccessLevel
	}
	return 0
}

type UpdateNEXAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NexAccount    *NEXAccount            `protobuf:"bytes,1,opt,name=nex_account,json=nexAccount,proto3" json:"nex_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNEXAccountResponse) Reset() {
	*x = UpdateNEXAccountResponse{}
	mi := &file_account_v2_update_nex_account_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNEXAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNEXAccountResponse) ProtoMessage() {}

func (x *UpdateNEXAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_nex_account_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNEXAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateNEXAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_update_nex_account_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNEXAccountResponse) GetNexAccount() *NEXAccount {
	if x != nil {
		return x.NexAccount
	}
	return nil
}

var File_account_v2_update_nex_account_rpc_proto protoreflect.FileDescriptor

const file_account_v2_update_nex_account_rpc_proto_rawDesc = "" +
	"\n" +
	"'account/v2/update_nex_account_rpc.proto\x12\n" +
	"account.v2\x1a\x1caccount/v2/nex_account.proto\"\xb1\x01\n" +
	"\x17UpdateNEXAccountRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x123\n" +
	"\x13server_access_level\x18\x02 \x01(\tH\x00R\x11serverAccessLevel\x88\x01\x01\x12&\n" +
	"\faccess_level\x18\x03 \x01(\x05H\x01R\vaccessLevel\x88\x01\x01B\x16\n" +
	"\x14_server_access_levelB\x0f\n" +
	"\r_access_level\"S\n" +
	"\x18UpdateNEXAccountResponse\x127\n" +
	"\vnex_account\x18\x01 \x01(\v2\x16.account.v2.NEXAccountR\n" +
	"nexAccountB\xac\x01\n" +
	"\x0ecom.account.v2B\x18UpdateNexAccountRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_update_nex_account_rpc_proto_rawDescOnce sync.Once
	file_account_v2_update_nex_account_rpc_proto_rawDescData []byte
)

func file_account_v2_update_nex_account_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_update_nex_account_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_update_nex_account_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_update_nex_account_rpc_proto_rawDesc), len(file_account_v2_update_nex_account_rpc_proto_rawDesc)))
	})
	return file_account_v2_update_nex_account_rpc_proto_rawDescData
}

var file_account_v2_update_nex_account_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_update_nex_account_rpc_proto_goTypes = []any{
	(*UpdateNEXAccountRequest)(nil),  // 0: account.v2.UpdateNEXAccountRequest
	(*UpdateNEXAccountResponse)(nil), // 1: account.v2.UpdateNEXAccountResponse
	(*NEXAccount)(nil),               // 2: account.v2.NEXAccount
}
var file_account_v2_update_nex_account_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.UpdateNEXAccountResponse.nex_account:type_name -> account.v2.NEXAccount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_v2_update_nex_account_rpc_proto_init() }
func file_account_v2_update_nex_account_rpc_proto_init() {
	if File_account_v2_update_nex_account_rpc_proto != nil {
		return
	}
	file_account_v2_nex_account_proto_init()
	file_account_v2_update_nex_account_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_update_nex_account_rpc_proto_rawDesc), len(file_account_v2_update_nex_account_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_update_nex_account_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_update_nex_account_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_update_nex_account_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_update_nex_account_rpc_proto = out.File
	file_account_v2_update_nex_account_rpc_proto_goTypes = nil
	file_account_v2_update_nex_account_rpc_proto_depIdxs = nil
}
