// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/update_ban_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateBanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ScopeType     *BanScopeType          `protobuf:"varint,6,opt,name=scope_type,json=scopeType,proto3,enum=account.v2.BanScopeType,oneof" json:"scope_type,omitempty"`
	ScopeTarget   *string                `protobuf:"bytes,7,opt,name=scope_target,json=scopeTarget,proto3,oneof" json:"scope_target,omitempty"`
	Reason        *string                `protobuf:"bytes,8,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	PardonReason  *string                `protobuf:"bytes,9,opt,name=pardon_reason,json=pardonReason,proto3,oneof" json:"pardon_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBanRequest) Reset() {
	*x = UpdateBanRequest{}
	mi := &file_account_v2_update_ban_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBanRequest) ProtoMessage() {}

func (x *UpdateBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_ban_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBanRequest.ProtoReflect.Descriptor instead.
func (*UpdateBanRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_update_ban_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBanRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateBanRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateBanRequest) GetScopeType() BanScopeType {
	if x != nil && x.ScopeType != nil {
		return *x.ScopeType
	}
	return BanScopeType_BAN_SCOPE_TYPE_UNSPECIFIED
}

func (x *UpdateBanRequest) GetScopeTarget() string {
	if x != nil && x.ScopeTarget != nil {
		return *x.ScopeTarget
	}
	return ""
}

func (x *UpdateBanRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *UpdateBanRequest) GetPardonReason() string {
	if x != nil && x.PardonReason != nil {
		return *x.PardonReason
	}
	return ""
}

type UpdateBanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ban           *Ban                   `protobuf:"bytes,1,opt,name=ban,proto3" json:"ban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBanResponse) Reset() {
	*x = UpdateBanResponse{}
	mi := &file_account_v2_update_ban_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBanResponse) ProtoMessage() {}

func (x *UpdateBanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_ban_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBanResponse.ProtoReflect.Descriptor instead.
func (*UpdateBanResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_update_ban_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBanResponse) GetBan() *Ban {
	if x != nil {
		return x.Ban
	}
	return nil
}

var File_account_v2_update_ban_rpc_proto protoreflect.FileDescriptor

const file_account_v2_update_ban_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1faccount/v2/update_ban_rpc.proto\x12\n" +
	"account.v2\x1a\x1caccount/v2/ban_details.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x03\n" +
	"\x10UpdateBanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendDate\x88\x01\x01\x12<\n" +
	"\n" +
	"scope_type\x18\x06 \x01(\x0e2\x18.account.v2.BanScopeTypeH\x02R\tscopeType\x88\x01\x01\x12&\n" +
	"\fscope_target\x18\a \x01(\tH\x03R\vscopeTarget\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\b \x01(\tH\x04R\x06reason\x88\x01\x01\x12(\n" +
	"\rpardon_reason\x18\t \x01(\tH\x05R\fpardonReason\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\r\n" +
	"\v_scope_typeB\x0f\n" +
	"\r_scope_targetB\t\n" +
	"\a_reasonB\x10\n" +
	"\x0e_pardon_reason\"6\n" +
	"\x11UpdateBanResponse\x12!\n" +
	"\x03ban\x18\x01 \x01(\v2\x0f.account.v2.BanR\x03banB\xa5\x01\n" +
	"\x0ecom.account.v2B\x11UpdateBanRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_update_ban_rpc_proto_rawDescOnce sync.Once
	file_account_v2_update_ban_rpc_proto_rawDescData []byte
)

func file_account_v2_update_ban_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_update_ban_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_update_ban_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_update_ban_rpc_proto_rawDesc), len(file_account_v2_update_ban_rpc_proto_rawDesc)))
	})
	return file_account_v2_update_ban_rpc_proto_rawDescData
}

var file_account_v2_update_ban_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_update_ban_rpc_proto_goTypes = []any{
	(*UpdateBanRequest)(nil),      // 0: account.v2.UpdateBanRequest
	(*UpdateBanResponse)(nil),     // 1: account.v2.UpdateBanResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(BanScopeType)(0),             // 3: account.v2.BanScopeType
	(*Ban)(nil),                   // 4: account.v2.Ban
}
var file_account_v2_update_ban_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.UpdateBanRequest.start_date:type_name -> google.protobuf.Timestamp
	2, // 1: account.v2.UpdateBanRequest.end_date:type_name -> google.protobuf.Timestamp
	3, // 2: account.v2.UpdateBanRequest.scope_type:type_name -> account.v2.BanScopeType
	4, // 3: account.v2.UpdateBanResponse.ban:type_name -> account.v2.Ban
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_account_v2_update_ban_rpc_proto_init() }
func file_account_v2_update_ban_rpc_proto_init() {
	if File_account_v2_update_ban_rpc_proto != nil {
		return
	}
	file_account_v2_ban_details_proto_init()
	file_account_v2_update_ban_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_update_ban_rpc_proto_rawDesc), len(file_account_v2_update_ban_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_update_ban_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_update_ban_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_update_ban_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_update_ban_rpc_proto = out.File
	file_account_v2_update_ban_rpc_proto_goTypes = nil
	file_account_v2_update_ban_rpc_proto_depIdxs = nil
}
