// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v2/update_device_rpc.proto

package accountv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDeviceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceId          uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServerAccessLevel *string                `protobuf:"bytes,2,opt,name=server_access_level,json=serverAccessLevel,proto3,oneof" json:"server_access_level,omitempty"`
	AccessLevel       *int32                 `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,oneof" json:"access_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_account_v2_update_device_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_device_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_update_device_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDeviceRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *UpdateDeviceRequest) GetServerAccessLevel() string {
	if x != nil && x.ServerAccessLevel != nil {
		return *x.ServerAccessLevel
	}
	return ""
}

func (x *UpdateDeviceRequest) GetAccessLevel() int32 {
	if x != nil && x.AccessLevel != nil {
		return *x.AccessLevel
	}
	return 0
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_account_v2_update_device_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_update_device_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_update_device_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_account_v2_update_device_rpc_proto protoreflect.FileDescriptor

const file_account_v2_update_device_rpc_proto_rawDesc = "" +
	"\n" +
	"\"account/v2/update_device_rpc.proto\x12\n" +
	"account.v2\x1a\x17account/v2/device.proto\"\xb8\x01\n" +
	"\x13UpdateDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x123\n" +
	"\x13server_access_level\x18\x02 \x01(\tH\x00R\x11serverAccessLevel\x88\x01\x01\x12&\n" +
	"\faccess_level\x18\x03 \x01(\x05H\x01R\vaccessLevel\x88\x01\x01B\x16\n" +
	"\x14_server_access_levelB\x0f\n" +
	"\r_access_level\"B\n" +
	"\x14UpdateDeviceResponse\x12*\n" +
	"\x06device\x18\x01 \x01(\v2\x12.account.v2.DeviceR\x06deviceB\xa8\x01\n" +
	"\x0ecom.account.v2B\x14UpdateDeviceRpcProtoP\x01Z7github.com/PretendoNetwork/grpc/go/account/v2;accountv2\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V2\xca\x02\n" +
	"Account\\V2\xe2\x02\x16Account\\V2\\GPBMetadata\xea\x02\vAccount::V2b\x06proto3"

var (
	file_account_v2_update_device_rpc_proto_rawDescOnce sync.Once
	file_account_v2_update_device_rpc_proto_rawDescData []byte
)

func file_account_v2_update_device_rpc_proto_rawDescGZIP() []byte {
	file_account_v2_update_device_rpc_proto_rawDescOnce.Do(func() {
		file_account_v2_update_device_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_update_device_rpc_proto_rawDesc), len(file_account_v2_update_device_rpc_proto_rawDesc)))
	})
	return file_account_v2_update_device_rpc_proto_rawDescData
}

var file_account_v2_update_device_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_v2_update_device_rpc_proto_goTypes = []any{
	(*UpdateDeviceRequest)(nil),  // 0: account.v2.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil), // 1: account.v2.UpdateDeviceResponse
	(*Device)(nil),               // 2: account.v2.Device
}
var file_account_v2_update_device_rpc_proto_depIdxs = []int32{
	2, // 0: account.v2.UpdateDeviceResponse.device:type_name -> account.v2.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_v2_update_device_rpc_proto_init() }
func file_account_v2_update_device_rpc_proto_init() {
	if File_account_v2_update_device_rpc_proto != nil {
		return
	}
	file_account_v2_device_proto_init()
	file_account_v2_update_device_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_update_device_rpc_proto_rawDesc), len(file_account_v2_update_device_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v2_update_device_rpc_proto_goTypes,
		DependencyIndexes: file_account_v2_update_device_rpc_proto_depIdxs,
		MessageInfos:      file_account_v2_update_device_rpc_proto_msgTypes,
	}.Build()
	File_account_v2_update_device_rpc_proto = out.File
	file_account_v2_update_device_rpc_proto_goTypes = nil
	file_account_v2_update_device_rpc_proto_depIdxs = nil
}
