// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: smm/v1/delete_course_rpc.proto

package smmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        uint64                 `protobuf:"varint,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_smm_v1_delete_course_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smm_v1_delete_course_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_smm_v1_delete_course_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteCourseRequest) GetDataId() uint64 {
	if x != nil {
		return x.DataId
	}
	return 0
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CourseName    string                 `protobuf:"bytes,2,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_smm_v1_delete_course_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smm_v1_delete_course_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_smm_v1_delete_course_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCourseResponse) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

var File_smm_v1_delete_course_rpc_proto protoreflect.FileDescriptor

const file_smm_v1_delete_course_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1esmm/v1/delete_course_rpc.proto\x12\x06smm.v1\".\n" +
	"\x13DeleteCourseRequest\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\x04R\x06dataId\"Q\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vcourse_name\x18\x02 \x01(\tR\n" +
	"courseNameB\x8c\x01\n" +
	"\n" +
	"com.smm.v1B\x14DeleteCourseRpcProtoP\x01Z/github.com/PretendoNetwork/grpc/go/smm/v1;smmv1\xa2\x02\x03SXX\xaa\x02\x06Smm.V1\xca\x02\x06Smm\\V1\xe2\x02\x12Smm\\V1\\GPBMetadata\xea\x02\aSmm::V1b\x06proto3"

var (
	file_smm_v1_delete_course_rpc_proto_rawDescOnce sync.Once
	file_smm_v1_delete_course_rpc_proto_rawDescData []byte
)

func file_smm_v1_delete_course_rpc_proto_rawDescGZIP() []byte {
	file_smm_v1_delete_course_rpc_proto_rawDescOnce.Do(func() {
		file_smm_v1_delete_course_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smm_v1_delete_course_rpc_proto_rawDesc), len(file_smm_v1_delete_course_rpc_proto_rawDesc)))
	})
	return file_smm_v1_delete_course_rpc_proto_rawDescData
}

var file_smm_v1_delete_course_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smm_v1_delete_course_rpc_proto_goTypes = []any{
	(*DeleteCourseRequest)(nil),  // 0: smm.v1.DeleteCourseRequest
	(*DeleteCourseResponse)(nil), // 1: smm.v1.DeleteCourseResponse
}
var file_smm_v1_delete_course_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smm_v1_delete_course_rpc_proto_init() }
func file_smm_v1_delete_course_rpc_proto_init() {
	if File_smm_v1_delete_course_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smm_v1_delete_course_rpc_proto_rawDesc), len(file_smm_v1_delete_course_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smm_v1_delete_course_rpc_proto_goTypes,
		DependencyIndexes: file_smm_v1_delete_course_rpc_proto_depIdxs,
		MessageInfos:      file_smm_v1_delete_course_rpc_proto_msgTypes,
	}.Build()
	File_smm_v1_delete_course_rpc_proto = out.File
	file_smm_v1_delete_course_rpc_proto_goTypes = nil
	file_smm_v1_delete_course_rpc_proto_depIdxs = nil
}
