// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: smm/v1/smm_service.proto

package smmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_smm_v1_smm_service_proto protoreflect.FileDescriptor

const file_smm_v1_smm_service_proto_rawDesc = "" +
	"\n" +
	"\x18smm/v1/smm_service.proto\x12\x06smm.v1\x1a\x1esmm/v1/delete_course_rpc.proto2Y\n" +
	"\n" +
	"SMMService\x12K\n" +
	"\fDeleteCourse\x12\x1b.smm.v1.DeleteCourseRequest\x1a\x1c.smm.v1.DeleteCourseResponse\"\x00B\x87\x01\n" +
	"\n" +
	"com.smm.v1B\x0fSmmServiceProtoP\x01Z/github.com/PretendoNetwork/grpc/go/smm/v1;smmv1\xa2\x02\x03SXX\xaa\x02\x06Smm.V1\xca\x02\x06Smm\\V1\xe2\x02\x12Smm\\V1\\GPBMetadata\xea\x02\aSmm::V1b\x06proto3"

var file_smm_v1_smm_service_proto_goTypes = []any{
	(*DeleteCourseRequest)(nil),  // 0: smm.v1.DeleteCourseRequest
	(*DeleteCourseResponse)(nil), // 1: smm.v1.DeleteCourseResponse
}
var file_smm_v1_smm_service_proto_depIdxs = []int32{
	0, // 0: smm.v1.SMMService.DeleteCourse:input_type -> smm.v1.DeleteCourseRequest
	1, // 1: smm.v1.SMMService.DeleteCourse:output_type -> smm.v1.DeleteCourseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smm_v1_smm_service_proto_init() }
func file_smm_v1_smm_service_proto_init() {
	if File_smm_v1_smm_service_proto != nil {
		return
	}
	file_smm_v1_delete_course_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smm_v1_smm_service_proto_rawDesc), len(file_smm_v1_smm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smm_v1_smm_service_proto_goTypes,
		DependencyIndexes: file_smm_v1_smm_service_proto_depIdxs,
	}.Build()
	File_smm_v1_smm_service_proto = out.File
	file_smm_v1_smm_service_proto_goTypes = nil
	file_smm_v1_smm_service_proto_depIdxs = nil
}
