// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: miiverse/v2/miiverse_service.proto

package miiversev2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_miiverse_v2_miiverse_service_proto protoreflect.FileDescriptor

const file_miiverse_v2_miiverse_service_proto_rawDesc = "" +
	"\n" +
	"\"miiverse/v2/miiverse_service.proto\x12\vmiiverse.v2\x1a)miiverse/v2/delete_account_data_rpc.proto\x1a)miiverse/v2/smm_request_post_id_rpc.proto2\xda\x01\n" +
	"\x0fMiiverseService\x12d\n" +
	"\x11DeleteAccountData\x12%.miiverse.v2.DeleteAccountDataRequest\x1a&.miiverse.v2.DeleteAccountDataResponse\"\x00\x12a\n" +
	"\x10SMMRequestPostId\x12$.miiverse.v2.SMMRequestPostIdRequest\x1a%.miiverse.v2.SMMRequestPostIdResponse\"\x00B\xaf\x01\n" +
	"\x0fcom.miiverse.v2B\x14MiiverseServiceProtoP\x01Z9github.com/PretendoNetwork/grpc/go/miiverse/v2;miiversev2\xa2\x02\x03MXX\xaa\x02\vMiiverse.V2\xca\x02\vMiiverse\\V2\xe2\x02\x17Miiverse\\V2\\GPBMetadata\xea\x02\fMiiverse::V2b\x06proto3"

var file_miiverse_v2_miiverse_service_proto_goTypes = []any{
	(*DeleteAccountDataRequest)(nil),  // 0: miiverse.v2.DeleteAccountDataRequest
	(*SMMRequestPostIdRequest)(nil),   // 1: miiverse.v2.SMMRequestPostIdRequest
	(*DeleteAccountDataResponse)(nil), // 2: miiverse.v2.DeleteAccountDataResponse
	(*SMMRequestPostIdResponse)(nil),  // 3: miiverse.v2.SMMRequestPostIdResponse
}
var file_miiverse_v2_miiverse_service_proto_depIdxs = []int32{
	0, // 0: miiverse.v2.MiiverseService.DeleteAccountData:input_type -> miiverse.v2.DeleteAccountDataRequest
	1, // 1: miiverse.v2.MiiverseService.SMMRequestPostId:input_type -> miiverse.v2.SMMRequestPostIdRequest
	2, // 2: miiverse.v2.MiiverseService.DeleteAccountData:output_type -> miiverse.v2.DeleteAccountDataResponse
	3, // 3: miiverse.v2.MiiverseService.SMMRequestPostId:output_type -> miiverse.v2.SMMRequestPostIdResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_miiverse_v2_miiverse_service_proto_init() }
func file_miiverse_v2_miiverse_service_proto_init() {
	if File_miiverse_v2_miiverse_service_proto != nil {
		return
	}
	file_miiverse_v2_delete_account_data_rpc_proto_init()
	file_miiverse_v2_smm_request_post_id_rpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_miiverse_v2_miiverse_service_proto_rawDesc), len(file_miiverse_v2_miiverse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_miiverse_v2_miiverse_service_proto_goTypes,
		DependencyIndexes: file_miiverse_v2_miiverse_service_proto_depIdxs,
	}.Build()
	File_miiverse_v2_miiverse_service_proto = out.File
	file_miiverse_v2_miiverse_service_proto_goTypes = nil
	file_miiverse_v2_miiverse_service_proto_depIdxs = nil
}
