// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/reset_password_rpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Password        string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm string                 `protobuf:"bytes,2,opt,name=password_confirm,json=passwordConfirm,proto3" json:"password_confirm,omitempty"`
	Token           string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_api_reset_password_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reset_password_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_reset_password_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordRequest) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_reset_password_rpc_proto protoreflect.FileDescriptor

const file_api_reset_password_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1capi/reset_password_rpc.proto\x12\x03api\"s\n" +
	"\x14ResetPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12)\n" +
	"\x10password_confirm\x18\x02 \x01(\tR\x0fpasswordConfirm\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05tokenBt\n" +
	"\acom.apiB\x15ResetPasswordRpcProtoP\x01Z&github.com/PretendoNetwork/grpc/go/api\xa2\x02\x03AXX\xaa\x02\x03Api\xca\x02\x03Api\xe2\x02\x0fApi\\GPBMetadata\xea\x02\x03Apib\x06proto3"

var (
	file_api_reset_password_rpc_proto_rawDescOnce sync.Once
	file_api_reset_password_rpc_proto_rawDescData []byte
)

func file_api_reset_password_rpc_proto_rawDescGZIP() []byte {
	file_api_reset_password_rpc_proto_rawDescOnce.Do(func() {
		file_api_reset_password_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reset_password_rpc_proto_rawDesc), len(file_api_reset_password_rpc_proto_rawDesc)))
	})
	return file_api_reset_password_rpc_proto_rawDescData
}

var file_api_reset_password_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_reset_password_rpc_proto_goTypes = []any{
	(*ResetPasswordRequest)(nil), // 0: api.ResetPasswordRequest
}
var file_api_reset_password_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_reset_password_rpc_proto_init() }
func file_api_reset_password_rpc_proto_init() {
	if File_api_reset_password_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reset_password_rpc_proto_rawDesc), len(file_api_reset_password_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_reset_password_rpc_proto_goTypes,
		DependencyIndexes: file_api_reset_password_rpc_proto_depIdxs,
		MessageInfos:      file_api_reset_password_rpc_proto_msgTypes,
	}.Build()
	File_api_reset_password_rpc_proto = out.File
	file_api_reset_password_rpc_proto_goTypes = nil
	file_api_reset_password_rpc_proto_depIdxs = nil
}
