// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/account_service.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_account_service_proto protoreflect.FileDescriptor

const file_account_account_service_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/account_service.proto\x12\aaccount\x1a*account/exchange_token_for_user_data.proto\x1a\x1eaccount/get_nex_data_rpc.proto\x1a\"account/get_nex_password_rpc.proto\x1a\x1faccount/get_user_data_rpc.proto\x1a%account/update_pnid_permissions.proto\x1a\x1bgoogle/protobuf/empty.proto2\xb3\x03\n" +
	"\aAccount\x12J\n" +
	"\vGetUserData\x12\x1b.account.GetUserDataRequest\x1a\x1c.account.GetUserDataResponse\"\x00\x12S\n" +
	"\x0eGetNEXPassword\x12\x1e.account.GetNEXPasswordRequest\x1a\x1f.account.GetNEXPasswordResponse\"\x00\x12G\n" +
	"\n" +
	"GetNEXData\x12\x1a.account.GetNEXDataRequest\x1a\x1b.account.GetNEXDataResponse\"\x00\x12X\n" +
	"\x15UpdatePNIDPermissions\x12%.account.UpdatePNIDPermissionsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12d\n" +
	"\x18ExchangeTokenForUserData\x12(.account.ExchangeTokenForUserDataRequest\x1a\x1c.account.GetUserDataResponse\"\x00B\x8a\x01\n" +
	"\vcom.accountB\x13AccountServiceProtoP\x01Z*github.com/PretendoNetwork/grpc/go/account\xa2\x02\x03AXX\xaa\x02\aAccount\xca\x02\aAccount\xe2\x02\x13Account\\GPBMetadata\xea\x02\aAccountb\x06proto3"

var file_account_account_service_proto_goTypes = []any{
	(*GetUserDataRequest)(nil),              // 0: account.GetUserDataRequest
	(*GetNEXPasswordRequest)(nil),           // 1: account.GetNEXPasswordRequest
	(*GetNEXDataRequest)(nil),               // 2: account.GetNEXDataRequest
	(*UpdatePNIDPermissionsRequest)(nil),    // 3: account.UpdatePNIDPermissionsRequest
	(*ExchangeTokenForUserDataRequest)(nil), // 4: account.ExchangeTokenForUserDataRequest
	(*GetUserDataResponse)(nil),             // 5: account.GetUserDataResponse
	(*GetNEXPasswordResponse)(nil),          // 6: account.GetNEXPasswordResponse
	(*GetNEXDataResponse)(nil),              // 7: account.GetNEXDataResponse
	(*emptypb.Empty)(nil),                   // 8: google.protobuf.Empty
}
var file_account_account_service_proto_depIdxs = []int32{
	0, // 0: account.Account.GetUserData:input_type -> account.GetUserDataRequest
	1, // 1: account.Account.GetNEXPassword:input_type -> account.GetNEXPasswordRequest
	2, // 2: account.Account.GetNEXData:input_type -> account.GetNEXDataRequest
	3, // 3: account.Account.UpdatePNIDPermissions:input_type -> account.UpdatePNIDPermissionsRequest
	4, // 4: account.Account.ExchangeTokenForUserData:input_type -> account.ExchangeTokenForUserDataRequest
	5, // 5: account.Account.GetUserData:output_type -> account.GetUserDataResponse
	6, // 6: account.Account.GetNEXPassword:output_type -> account.GetNEXPasswordResponse
	7, // 7: account.Account.GetNEXData:output_type -> account.GetNEXDataResponse
	8, // 8: account.Account.UpdatePNIDPermissions:output_type -> google.protobuf.Empty
	5, // 9: account.Account.ExchangeTokenForUserData:output_type -> account.GetUserDataResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_account_service_proto_init() }
func file_account_account_service_proto_init() {
	if File_account_account_service_proto != nil {
		return
	}
	file_account_exchange_token_for_user_data_proto_init()
	file_account_get_nex_data_rpc_proto_init()
	file_account_get_nex_password_rpc_proto_init()
	file_account_get_user_data_rpc_proto_init()
	file_account_update_pnid_permissions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_service_proto_rawDesc), len(file_account_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_account_service_proto_goTypes,
		DependencyIndexes: file_account_account_service_proto_depIdxs,
	}.Build()
	File_account_account_service_proto = out.File
	file_account_account_service_proto_goTypes = nil
	file_account_account_service_proto_depIdxs = nil
}
