// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/update_pnid_permissions.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePNIDPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Permissions   *PNIDPermissionFlags   `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePNIDPermissionsRequest) Reset() {
	*x = UpdatePNIDPermissionsRequest{}
	mi := &file_account_update_pnid_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePNIDPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePNIDPermissionsRequest) ProtoMessage() {}

func (x *UpdatePNIDPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_update_pnid_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePNIDPermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePNIDPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_account_update_pnid_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePNIDPermissionsRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdatePNIDPermissionsRequest) GetPermissions() *PNIDPermissionFlags {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_account_update_pnid_permissions_proto protoreflect.FileDescriptor

const file_account_update_pnid_permissions_proto_rawDesc = "" +
	"\n" +
	"%account/update_pnid_permissions.proto\x12\aaccount\x1a#account/pnid_permission_flags.proto\"p\n" +
	"\x1cUpdatePNIDPermissionsRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12>\n" +
	"\vpermissions\x18\x02 \x01(\v2\x1c.account.PNIDPermissionFlagsR\vpermissionsB\x91\x01\n" +
	"\vcom.accountB\x1aUpdatePnidPermissionsProtoP\x01Z*github.com/PretendoNetwork/grpc/go/account\xa2\x02\x03AXX\xaa\x02\aAccount\xca\x02\aAccount\xe2\x02\x13Account\\GPBMetadata\xea\x02\aAccountb\x06proto3"

var (
	file_account_update_pnid_permissions_proto_rawDescOnce sync.Once
	file_account_update_pnid_permissions_proto_rawDescData []byte
)

func file_account_update_pnid_permissions_proto_rawDescGZIP() []byte {
	file_account_update_pnid_permissions_proto_rawDescOnce.Do(func() {
		file_account_update_pnid_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_update_pnid_permissions_proto_rawDesc), len(file_account_update_pnid_permissions_proto_rawDesc)))
	})
	return file_account_update_pnid_permissions_proto_rawDescData
}

var file_account_update_pnid_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_update_pnid_permissions_proto_goTypes = []any{
	(*UpdatePNIDPermissionsRequest)(nil), // 0: account.UpdatePNIDPermissionsRequest
	(*PNIDPermissionFlags)(nil),          // 1: account.PNIDPermissionFlags
}
var file_account_update_pnid_permissions_proto_depIdxs = []int32{
	1, // 0: account.UpdatePNIDPermissionsRequest.permissions:type_name -> account.PNIDPermissionFlags
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_update_pnid_permissions_proto_init() }
func file_account_update_pnid_permissions_proto_init() {
	if File_account_update_pnid_permissions_proto != nil {
		return
	}
	file_account_pnid_permission_flags_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_update_pnid_permissions_proto_rawDesc), len(file_account_update_pnid_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_update_pnid_permissions_proto_goTypes,
		DependencyIndexes: file_account_update_pnid_permissions_proto_depIdxs,
		MessageInfos:      file_account_update_pnid_permissions_proto_msgTypes,
	}.Build()
	File_account_update_pnid_permissions_proto = out.File
	file_account_update_pnid_permissions_proto_goTypes = nil
	file_account_update_pnid_permissions_proto_depIdxs = nil
}
