// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: friends/friend_request.proto

package friends

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        uint32                 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     uint32                 `protobuf:"varint,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sent          uint64                 `protobuf:"varint,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Expires       uint64                 `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_friends_friend_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friend_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_friends_friend_request_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *FriendRequest) GetRecipient() uint32 {
	if x != nil {
		return x.Recipient
	}
	return 0
}

func (x *FriendRequest) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *FriendRequest) GetExpires() uint64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *FriendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_friends_friend_request_proto protoreflect.FileDescriptor

const file_friends_friend_request_proto_rawDesc = "" +
	"\n" +
	"\x1cfriends/friend_request.proto\x12\afriends\"\x9d\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\rR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\rR\trecipient\x12\x12\n" +
	"\x04sent\x18\x04 \x01(\x04R\x04sent\x12\x18\n" +
	"\aexpires\x18\x05 \x01(\x04R\aexpires\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessageB\x89\x01\n" +
	"\vcom.friendsB\x12FriendRequestProtoP\x01Z*github.com/PretendoNetwork/grpc/go/friends\xa2\x02\x03FXX\xaa\x02\aFriends\xca\x02\aFriends\xe2\x02\x13Friends\\GPBMetadata\xea\x02\aFriendsb\x06proto3"

var (
	file_friends_friend_request_proto_rawDescOnce sync.Once
	file_friends_friend_request_proto_rawDescData []byte
)

func file_friends_friend_request_proto_rawDescGZIP() []byte {
	file_friends_friend_request_proto_rawDescOnce.Do(func() {
		file_friends_friend_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_friend_request_proto_rawDesc), len(file_friends_friend_request_proto_rawDesc)))
	})
	return file_friends_friend_request_proto_rawDescData
}

var file_friends_friend_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_friends_friend_request_proto_goTypes = []any{
	(*FriendRequest)(nil), // 0: friends.FriendRequest
}
var file_friends_friend_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friends_friend_request_proto_init() }
func file_friends_friend_request_proto_init() {
	if File_friends_friend_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_friend_request_proto_rawDesc), len(file_friends_friend_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friends_friend_request_proto_goTypes,
		DependencyIndexes: file_friends_friend_request_proto_depIdxs,
		MessageInfos:      file_friends_friend_request_proto_msgTypes,
	}.Build()
	File_friends_friend_request_proto = out.File
	file_friends_friend_request_proto_goTypes = nil
	file_friends_friend_request_proto_depIdxs = nil
}
