// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/delete_file.proto

package boss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        uint64                 `protobuf:"varint,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_boss_delete_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_delete_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_boss_delete_file_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileRequest) GetDataId() uint64 {
	if x != nil {
		return x.DataId
	}
	return 0
}

func (x *DeleteFileRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

var File_boss_delete_file_proto protoreflect.FileDescriptor

const file_boss_delete_file_proto_rawDesc = "" +
	"\n" +
	"\x16boss/delete_file.proto\x12\x04boss\"L\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\x04R\x06dataId\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppIdBt\n" +
	"\bcom.bossB\x0fDeleteFileProtoP\x01Z'github.com/PretendoNetwork/grpc/go/boss\xa2\x02\x03BXX\xaa\x02\x04Boss\xca\x02\x04Boss\xe2\x02\x10Boss\\GPBMetadata\xea\x02\x04Bossb\x06proto3"

var (
	file_boss_delete_file_proto_rawDescOnce sync.Once
	file_boss_delete_file_proto_rawDescData []byte
)

func file_boss_delete_file_proto_rawDescGZIP() []byte {
	file_boss_delete_file_proto_rawDescOnce.Do(func() {
		file_boss_delete_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_delete_file_proto_rawDesc), len(file_boss_delete_file_proto_rawDesc)))
	})
	return file_boss_delete_file_proto_rawDescData
}

var file_boss_delete_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_boss_delete_file_proto_goTypes = []any{
	(*DeleteFileRequest)(nil), // 0: boss.DeleteFileRequest
}
var file_boss_delete_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boss_delete_file_proto_init() }
func file_boss_delete_file_proto_init() {
	if File_boss_delete_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_delete_file_proto_rawDesc), len(file_boss_delete_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_delete_file_proto_goTypes,
		DependencyIndexes: file_boss_delete_file_proto_depIdxs,
		MessageInfos:      file_boss_delete_file_proto_msgTypes,
	}.Build()
	File_boss_delete_file_proto = out.File
	file_boss_delete_file_proto_goTypes = nil
	file_boss_delete_file_proto_depIdxs = nil
}
