// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/list_known_boss_apps.proto

package boss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BOSSApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BossAppId     string                 `protobuf:"bytes,1,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	TitleId       string                 `protobuf:"bytes,2,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	TitleRegion   string                 `protobuf:"bytes,3,opt,name=title_region,json=titleRegion,proto3" json:"title_region,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Tasks         []string               `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BOSSApp) Reset() {
	*x = BOSSApp{}
	mi := &file_boss_list_known_boss_apps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BOSSApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOSSApp) ProtoMessage() {}

func (x *BOSSApp) ProtoReflect() protoreflect.Message {
	mi := &file_boss_list_known_boss_apps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOSSApp.ProtoReflect.Descriptor instead.
func (*BOSSApp) Descriptor() ([]byte, []int) {
	return file_boss_list_known_boss_apps_proto_rawDescGZIP(), []int{0}
}

func (x *BOSSApp) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *BOSSApp) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *BOSSApp) GetTitleRegion() string {
	if x != nil {
		return x.TitleRegion
	}
	return ""
}

func (x *BOSSApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BOSSApp) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ListKnownBOSSAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*BOSSApp             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownBOSSAppsResponse) Reset() {
	*x = ListKnownBOSSAppsResponse{}
	mi := &file_boss_list_known_boss_apps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownBOSSAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownBOSSAppsResponse) ProtoMessage() {}

func (x *ListKnownBOSSAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_list_known_boss_apps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownBOSSAppsResponse.ProtoReflect.Descriptor instead.
func (*ListKnownBOSSAppsResponse) Descriptor() ([]byte, []int) {
	return file_boss_list_known_boss_apps_proto_rawDescGZIP(), []int{1}
}

func (x *ListKnownBOSSAppsResponse) GetApps() []*BOSSApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

var File_boss_list_known_boss_apps_proto protoreflect.FileDescriptor

const file_boss_list_known_boss_apps_proto_rawDesc = "" +
	"\n" +
	"\x1fboss/list_known_boss_apps.proto\x12\x04boss\"\x91\x01\n" +
	"\aBOSSApp\x12\x1e\n" +
	"\vboss_app_id\x18\x01 \x01(\tR\tbossAppId\x12\x19\n" +
	"\btitle_id\x18\x02 \x01(\tR\atitleId\x12!\n" +
	"\ftitle_region\x18\x03 \x01(\tR\vtitleRegion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05tasks\x18\x05 \x03(\tR\x05tasks\">\n" +
	"\x19ListKnownBOSSAppsResponse\x12!\n" +
	"\x04apps\x18\x01 \x03(\v2\r.boss.BOSSAppR\x04appsB{\n" +
	"\bcom.bossB\x16ListKnownBossAppsProtoP\x01Z'github.com/PretendoNetwork/grpc/go/boss\xa2\x02\x03BXX\xaa\x02\x04Boss\xca\x02\x04Boss\xe2\x02\x10Boss\\GPBMetadata\xea\x02\x04Bossb\x06proto3"

var (
	file_boss_list_known_boss_apps_proto_rawDescOnce sync.Once
	file_boss_list_known_boss_apps_proto_rawDescData []byte
)

func file_boss_list_known_boss_apps_proto_rawDescGZIP() []byte {
	file_boss_list_known_boss_apps_proto_rawDescOnce.Do(func() {
		file_boss_list_known_boss_apps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_list_known_boss_apps_proto_rawDesc), len(file_boss_list_known_boss_apps_proto_rawDesc)))
	})
	return file_boss_list_known_boss_apps_proto_rawDescData
}

var file_boss_list_known_boss_apps_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_list_known_boss_apps_proto_goTypes = []any{
	(*BOSSApp)(nil),                   // 0: boss.BOSSApp
	(*ListKnownBOSSAppsResponse)(nil), // 1: boss.ListKnownBOSSAppsResponse
}
var file_boss_list_known_boss_apps_proto_depIdxs = []int32{
	0, // 0: boss.ListKnownBOSSAppsResponse.apps:type_name -> boss.BOSSApp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_list_known_boss_apps_proto_init() }
func file_boss_list_known_boss_apps_proto_init() {
	if File_boss_list_known_boss_apps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_list_known_boss_apps_proto_rawDesc), len(file_boss_list_known_boss_apps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_list_known_boss_apps_proto_goTypes,
		DependencyIndexes: file_boss_list_known_boss_apps_proto_depIdxs,
		MessageInfos:      file_boss_list_known_boss_apps_proto_msgTypes,
	}.Build()
	File_boss_list_known_boss_apps_proto = out.File
	file_boss_list_known_boss_apps_proto_goTypes = nil
	file_boss_list_known_boss_apps_proto_depIdxs = nil
}
