// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boss/register_task.proto

package boss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BossAppId     string                 `protobuf:"bytes,2,opt,name=boss_app_id,json=bossAppId,proto3" json:"boss_app_id,omitempty"`
	TitleId       string                 `protobuf:"bytes,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskRequest) Reset() {
	*x = RegisterTaskRequest{}
	mi := &file_boss_register_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskRequest) ProtoMessage() {}

func (x *RegisterTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_register_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskRequest) Descriptor() ([]byte, []int) {
	return file_boss_register_task_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterTaskRequest) GetBossAppId() string {
	if x != nil {
		return x.BossAppId
	}
	return ""
}

func (x *RegisterTaskRequest) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *RegisterTaskRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegisterTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskResponse) Reset() {
	*x = RegisterTaskResponse{}
	mi := &file_boss_register_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResponse) ProtoMessage() {}

func (x *RegisterTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_register_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskResponse) Descriptor() ([]byte, []int) {
	return file_boss_register_task_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_boss_register_task_proto protoreflect.FileDescriptor

const file_boss_register_task_proto_rawDesc = "" +
	"\n" +
	"\x18boss/register_task.proto\x12\x04boss\x1a\x0fboss/task.proto\"\x9c\x01\n" +
	"\x13RegisterTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vboss_app_id\x18\x02 \x01(\tR\tbossAppId\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\tR\atitleId\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"6\n" +
	"\x14RegisterTaskResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".boss.TaskR\x04taskBv\n" +
	"\bcom.bossB\x11RegisterTaskProtoP\x01Z'github.com/PretendoNetwork/grpc/go/boss\xa2\x02\x03BXX\xaa\x02\x04Boss\xca\x02\x04Boss\xe2\x02\x10Boss\\GPBMetadata\xea\x02\x04Bossb\x06proto3"

var (
	file_boss_register_task_proto_rawDescOnce sync.Once
	file_boss_register_task_proto_rawDescData []byte
)

func file_boss_register_task_proto_rawDescGZIP() []byte {
	file_boss_register_task_proto_rawDescOnce.Do(func() {
		file_boss_register_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_register_task_proto_rawDesc), len(file_boss_register_task_proto_rawDesc)))
	})
	return file_boss_register_task_proto_rawDescData
}

var file_boss_register_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_boss_register_task_proto_goTypes = []any{
	(*RegisterTaskRequest)(nil),  // 0: boss.RegisterTaskRequest
	(*RegisterTaskResponse)(nil), // 1: boss.RegisterTaskResponse
	(*Task)(nil),                 // 2: boss.Task
}
var file_boss_register_task_proto_depIdxs = []int32{
	2, // 0: boss.RegisterTaskResponse.task:type_name -> boss.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_register_task_proto_init() }
func file_boss_register_task_proto_init() {
	if File_boss_register_task_proto != nil {
		return
	}
	file_boss_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_register_task_proto_rawDesc), len(file_boss_register_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_register_task_proto_goTypes,
		DependencyIndexes: file_boss_register_task_proto_depIdxs,
		MessageInfos:      file_boss_register_task_proto_msgTypes,
	}.Build()
	File_boss_register_task_proto = out.File
	file_boss_register_task_proto_goTypes = nil
	file_boss_register_task_proto_depIdxs = nil
}
